//! Tool dispatch middleware pipeline.
//!
//! Each middleware wraps the dispatch call and can inspect/modify the request before
//! execution and the result after execution.
//!
//! # Architecture
//!
//! ```text
//! [outer middleware .dispatch()]
//!   → pre-processing (inspect/modify context)
//!   → next.dispatch(ctx)
//!     → [inner middleware .dispatch()]
//!       → ...
//!       → [Innermost: ToolCallMiddleware → Tool::call()]
//!       → ...
//!   → post-processing (inspect/modify result)
//!   → return ToolDispatchResult
//! ```
//!
//! # Provided Middlewares
//!
//! | Middleware                | Description                                                       |
//! |---------------------------|-------------------------------------------------------------------|
//! | [`ToolCallMiddleware`]    | Innermost layer — looks up tool in registry, calls `Tool::call()` |
//! | [`PermissionMiddleware`]  | Checks [`PermissionCheck`] before execution                       |
//! | [`TimeoutMiddleware`]     | Wraps execution in a deadline with retry                          |
//! | [`UnknownToolMiddleware`] | Suggests closest matching tool on "not found"                     |
//!
//! # Example
//!
//! ```rust,ignore
//! use loopctl::engine::middleware::{
//!     ToolPipeline, ToolCallMiddleware, PermissionMiddleware, TimeoutMiddleware,
//! };
//! use loopctl::tool::ToolRegistry;
//! use std::sync::Arc;
//!
//! let registry = Arc::new(ToolRegistry::new());
//!
//! let pipeline = ToolPipeline::builder()
//!     .with(PermissionMiddleware::deny_all())
//!     .with(TimeoutMiddleware::from_secs(120))
//!     .core(registry)
//!     .build()
//!     .expect("pipeline configuration is valid");
//!
//! let result = pipeline.invoke(ctx).await;
//! ```

use crate::cancel::CancelSignal;
use crate::core::error::AgentError;
use crate::message::ToolContent;
use crate::tool::{PermissionCheck, ToolContext, ToolRegistry};
use serde_json::Value;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;
use std::time::{Duration, Instant};
use tracing;

// ===================================================
// Dispatch context and result
// ===================================================

/// Context passed through the middleware chain for a single tool invocation.
///
/// Built once per tool call by the framework, then threaded through each
/// middleware. Middlewares can read from and write to this struct.
///
/// # Fields
///
/// - [`tool_name`](ToolDispatchContext::tool_name) — Which tool is being called.
/// - [`input`](ToolDispatchContext::input) — The JSON input to the tool.
/// - [`call_id`](ToolDispatchContext::call_id) — Unique ID for this tool call.
/// - [`turn_number`](ToolDispatchContext::turn_number) — Turn number within the session.
/// - [`cancel`](ToolDispatchContext::cancel) — Shared cancellation signal.
/// - [`permission`](ToolDispatchContext::permission) — Permission state for this call.
/// - [`tool_context`](ToolDispatchContext::tool_context) — Context passed to the tool.
///
/// Session identity is available via [`tool_context.session_id`](ToolContext::session_id)
/// rather than duplicated on this struct.
pub struct ToolDispatchContext {
    /// Which tool is being called.
    ///
    /// Set by the framework from the model's tool call part.
    /// Middlewares can redirect to a different tool by modifying
    /// this field (e.g. a routing middleware).
    pub tool_name: String,

    /// The JSON input to the tool.
    ///
    /// The raw JSON value from the model's tool call part.
    /// Middlewares can inspect or transform this before the tool
    /// is invoked (e.g. sanitisation, validation, schema upgrade).
    pub input: Value,

    /// Unique ID for this tool call.
    ///
    /// Generated by the model provider and used to correlate tool
    /// results back to the originating tool call request.
    pub call_id: String,

    /// Turn number within the session.
    ///
    /// Monotonically increasing counter for the current conversation
    /// turn. Useful for logging and for middlewares that need to
    /// enforce per-turn limits.
    pub turn_number: usize,

    /// Shared cancellation signal — middlewares should check this
    /// before doing expensive work.
    ///
    /// Set by the framework when the user or a deadline triggers
    /// cancellation. Long-running middlewares (e.g. [`TimeoutMiddleware`])
    /// should cooperative-check this via `tokio::select!`.
    pub cancel: Arc<CancelSignal>,

    /// Permission state for this call.
    ///
    /// Set by the framework based on tool registration. Middlewares
    /// (e.g. [`PermissionMiddleware`]) can read and modify this.
    pub permission: PermissionCheck,

    /// Context passed to the underlying tool invocation.
    ///
    /// Middlewares can augment this (e.g. adding metadata) before
    /// the innermost [`ToolCallMiddleware`] invokes `Tool::call()`.
    pub tool_context: ToolContext,
}
// Re-export the unified tool dispatch result from core types.
// Defined in `crate::core::types` so it's available at both
// `loopctl::core::ToolDispatchResult` and
// `loopctl::engine::middleware::ToolDispatchResult`.
pub use crate::core::types::ToolDispatchResult;

// ===================================================
// Middleware trait
// ===================================================

/// The trait for a middleware in the tool dispatch pipeline.
///
/// Each middleware wraps the "next" dispatch layer. The outermost middleware
/// is called first; it can pre-process the context, call `next.dispatch()`,
/// then post-process the result. Or it can short-circuit by returning a
/// result without calling `next`.
///
/// # Ordering Conventions
///
/// The typical registration order is:
///
/// 1. [`PermissionMiddleware`] — deny before any work is done
/// 2. [`TimeoutMiddleware`] — wrap execution in a deadline
/// 3. [`UnknownToolMiddleware`] — intercept "not found" errors
/// 4. (innermost) [`ToolCallMiddleware`] — the actual `Tool::call()`
///
/// Post-processing middlewares (e.g. output limiting) are registered
/// *after* the core so they wrap the result on the way out.
///
/// # Example
///
/// ```rust,ignore
/// struct LoggingMiddleware;
///
/// impl ToolMiddleware for LoggingMiddleware {
///     fn name(&self) -> &str { "logging" }
///
///     fn dispatch(
///         &self,
///         ctx: &mut ToolDispatchContext,
///         next: &ToolPipeline,
///     ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + '_>> {
///         Box::pin(async move {
///             tracing::info!("before tool: {}", ctx.tool_name);
///             let result = next.dispatch(ctx).await;
///             tracing::info!("after tool: {} (error={})", ctx.tool_name, result.is_error);
///             result
///         })
///     }
/// }
/// ```
pub trait ToolMiddleware: Send + Sync {
    /// Human-readable name for this middleware.
    ///
    /// Used in logging, diagnostics, and error messages.
    fn name(&self) -> &str;

    /// Process a tool dispatch through this middleware layer.
    ///
    /// Call `next.dispatch(ctx)` to invoke the next layer in the pipeline.
    /// Return a [`ToolDispatchResult`] directly to short-circuit.
    fn dispatch<'a>(
        &'a self,
        ctx: &'a mut ToolDispatchContext,
        next: &'a ToolPipeline,
    ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + 'a>>;
}

/// Errors that can occur during pipeline construction.
#[derive(Debug, thiserror::Error)]
pub enum PipelineError {
    /// No core dispatch (tool registry) was provided.
    #[error("pipeline requires a core dispatch (call .core() with a ToolRegistry)")]
    MissingCore,

    /// The pipeline is empty — no middlewares and no core.
    #[error("pipeline has no middlewares and no core dispatch")]
    Empty,
}

// ===================================================
// Pipeline
// ===================================================

/// An assembled middleware pipeline for tool dispatch.
///
/// Holds an ordered list of [`ToolMiddleware`] layers around an innermost
/// [`ToolCallMiddleware`] that performs the actual tool invocation via a
/// [`ToolRegistry`]. An internal `index` cursor tracks the current position
/// during dispatch — the entry point starts at index 0, and each middleware
/// receives a pipeline advanced by one position as its `next`.
///
/// # Construction
///
/// Use [`ToolPipeline::builder()`] to create a [`ToolPipelineBuilder`],
/// add middlewares, set the core registry, and call [`build()`](ToolPipelineBuilder::build).
///
/// # Dispatch
///
/// - [`dispatch()`](ToolPipeline::dispatch) — execute a single tool call
///   through the full chain.
/// - [`dispatch_all()`](ToolPipeline::dispatch_all) — execute multiple tool
///   calls sequentially (parallel dispatch is planned).
///
/// # Example
///
/// ```rust,ignore
/// let pipeline = ToolPipeline::builder()
///     .with(PermissionMiddleware::deny_all())
///     .with(TimeoutMiddleware::from_secs(120))
///     .core(registry)
///     .build()
///     .expect("pipeline configuration is valid");
///
/// let result = pipeline.invoke(ctx).await;
/// ```
pub struct ToolPipeline {
    /// Ordered middleware layers (outermost first).
    middlewares: Arc<[Arc<dyn ToolMiddleware>]>,

    /// The innermost core dispatch that calls `Tool::call()`.
    core: Arc<ToolCallMiddleware>,

    /// Cursor position during dispatch.
    ///
    /// `0` at the entry point. Each middleware receives a pipeline
    /// at `index + 1` as its `next`.
    index: usize,
}

impl std::fmt::Debug for ToolPipeline {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ToolPipeline")
            .field("middleware_count", &self.middlewares.len())
            .field("middleware_names", &self.middleware_names())
            .finish_non_exhaustive()
    }
}

impl ToolPipeline {
    /// Create a new pipeline builder.
    ///
    /// Returns a [`ToolPipelineBuilder`] for fluent configuration.
    #[must_use]
    pub fn builder() -> ToolPipelineBuilder {
        ToolPipelineBuilder::new()
    }

    /// Create a minimal pipeline with only the core dispatch.
    ///
    /// Equivalent to `ToolPipeline::builder().core(registry).build().unwrap()`.
    /// Useful for cases where no middleware is needed (e.g. testing).
    #[must_use]
    pub fn new(registry: Arc<ToolRegistry>) -> Self {
        Self {
            middlewares: Arc::new([]),
            core: Arc::new(ToolCallMiddleware::new(registry)),
            index: 0,
        }
    }

    /// Dispatch to the middleware layer at the current cursor index.
    ///
    /// If `index` points past the middleware list, falls through to the
    /// core [`ToolCallMiddleware`]. Middlewares receive a pipeline advanced
    /// by one position as their `next` and call this method to continue
    /// the chain.
    pub fn dispatch<'a>(
        &'a self,
        ctx: &'a mut ToolDispatchContext,
    ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + 'a>> {
        let Some(middleware) = self.middlewares.get(self.index).cloned() else {
            let core = Arc::clone(&self.core);
            return Box::pin(async move { core.dispatch(ctx).await });
        };
        let next = ToolPipeline {
            middlewares: Arc::clone(&self.middlewares),
            core: Arc::clone(&self.core),
            index: self.index.saturating_add(1),
        };
        Box::pin(async move { middleware.dispatch(ctx, &next).await })
    }

    /// Invoke the full pipeline from the beginning.
    ///
    /// Always starts at index 0 regardless of the stored cursor — this
    /// ensures correct behavior even if called on a non-root pipeline.
    /// The cost is two `Arc::clone`s, which is negligible.
    pub async fn invoke(&self, mut ctx: ToolDispatchContext) -> ToolDispatchResult {
        let root = ToolPipeline {
            middlewares: Arc::clone(&self.middlewares),
            core: Arc::clone(&self.core),
            index: 0,
        };
        root.dispatch(&mut ctx).await
    }

    /// Dispatch multiple tool calls sequentially.
    ///
    /// Each call goes through the full middleware chain. Cancellation is
    /// checked between calls — if the signal is set, remaining calls
    /// are skipped and an [`AgentError::Cancelled`] is returned.
    ///
    /// Returns results in the same order as the input calls.
    ///
    /// # Errors
    ///
    /// Returns [`AgentError::Cancelled`] if the cancellation signal is
    /// set before all calls have been dispatched.
    pub async fn dispatch_all(
        &self,
        calls: Vec<ToolDispatchContext>,
    ) -> Result<Vec<ToolDispatchResult>, AgentError> {
        let mut results = Vec::with_capacity(calls.len());
        for ctx in calls {
            if ctx.cancel.is_cancelled() {
                return Err(AgentError::Cancelled);
            }
            let cancel = Arc::clone(&ctx.cancel);
            let result = self.invoke(ctx).await;
            if cancel.is_cancelled() {
                return Err(AgentError::Cancelled);
            }
            results.push(result);
        }
        Ok(results)
    }

    /// Get the names of all middleware layers in order.
    ///
    /// Useful for diagnostics and logging.
    #[must_use]
    pub fn middleware_names(&self) -> Vec<&str> {
        let mut names: Vec<&str> = self.middlewares.iter().map(|m| m.name()).collect();
        names.push(ToolCallMiddleware::NAME);
        names
    }
}

// ===================================================
// Pipeline builder
// ===================================================

/// Builds an ordered middleware pipeline for tool dispatch.
///
/// # Example
///
/// ```rust,ignore
/// let pipeline = ToolPipeline::builder()
///     .with(PermissionMiddleware::deny_all())
///     .with(TimeoutMiddleware::from_secs(120))
///     .core(Arc::new(tool_registry))
///     .build()
///     .expect("pipeline configuration is valid");
/// ```
pub struct ToolPipelineBuilder {
    middlewares: Vec<Arc<dyn ToolMiddleware>>,
    core: Option<Arc<ToolRegistry>>,
}

impl ToolPipelineBuilder {
    /// Create a new, empty builder.
    #[must_use]
    pub fn new() -> Self {
        Self {
            middlewares: Vec::new(),
            core: None,
        }
    }

    /// Add a middleware layer to the pipeline.
    ///
    /// Middlewares are executed in the order they are added (outermost first).
    /// The core dispatch is always the innermost layer.
    #[must_use]
    pub fn with<M: ToolMiddleware + 'static>(mut self, middleware: M) -> Self {
        self.middlewares.push(Arc::new(middleware));
        self
    }

    /// Add an already-`Arc`-wrapped middleware.
    ///
    /// Useful when the same middleware instance needs to be shared
    /// across multiple pipelines.
    #[must_use]
    pub fn with_arc(mut self, middleware: Arc<dyn ToolMiddleware>) -> Self {
        self.middlewares.push(middleware);
        self
    }

    /// Set the core tool registry for the pipeline.
    ///
    /// The registry is wrapped in a [`ToolCallMiddleware`] that performs
    /// the actual tool lookup and invocation. This is the innermost
    /// layer of the pipeline.
    #[must_use]
    pub fn core(mut self, registry: Arc<ToolRegistry>) -> Self {
        self.core = Some(registry);
        self
    }

    /// Build the pipeline.
    ///
    /// # Errors
    ///
    /// Returns [`PipelineError::MissingCore`] if no core registry was provided.
    pub fn build(self) -> Result<ToolPipeline, PipelineError> {
        let registry = self.core.ok_or(PipelineError::MissingCore)?;
        Ok(ToolPipeline {
            middlewares: self.middlewares.into(),
            core: Arc::new(ToolCallMiddleware::new(registry)),
            index: 0,
        })
    }
}

impl Default for ToolPipelineBuilder {
    fn default() -> Self {
        Self::new()
    }
}

// ===================================================
// ToolCallMiddleware (innermost core)
// ===================================================

/// The innermost middleware that performs the actual tool invocation.
///
/// Looks up the tool by name in the [`ToolRegistry`], calls
/// [`crate::tool::Tool::call()`], and converts the result into a
/// [`ToolDispatchResult`]. If the tool is not found, produces a
/// soft error result (not a hard error) so the model can recover.
///
/// This middleware is automatically created by the pipeline builder
/// and always occupies the innermost position in the chain.
pub struct ToolCallMiddleware {
    registry: Arc<ToolRegistry>,
}

impl ToolCallMiddleware {
    const NAME: &str = "tool_call";

    /// Create a new core dispatch wrapping the given registry.
    #[must_use]
    pub fn new(registry: Arc<ToolRegistry>) -> Self {
        Self { registry }
    }

    /// Execute the tool call — the terminal dispatch.
    ///
    /// Looks up the tool by name in the registry, calls `Tool::call()`,
    /// and converts the result. This is not a middleware — it has no
    /// `next` parameter because there is nothing to chain to.
    fn dispatch(
        &self,
        ctx: &mut ToolDispatchContext,
    ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + '_>> {
        let tool_name = ctx.tool_name.clone();
        let input = ctx.input.clone();
        let tool_ctx = ctx.tool_context.clone();
        let registry = Arc::clone(&self.registry);
        let cancel = Arc::clone(&ctx.cancel);

        Box::pin(async move {
            let start = Instant::now();
            let Some(tool) = registry.get(&tool_name) else {
                let available: Vec<String> = registry.tool_names();
                let available_refs: Vec<&str> = available.iter().map(String::as_str).collect();
                let error = AgentError::tool_not_found(&tool_name, &available_refs);
                return ToolDispatchResult::err(&tool_name, error.to_string(), start.elapsed());
            };

            let call_result = tokio::select! {
                r = tool.call(input, &tool_ctx) => r,
                () = cancel.notified() => {
                    return ToolDispatchResult::err(
                        &tool_name,
                        format!("Tool '{tool_name}' cancelled"),
                        start.elapsed(),
                    );
                }
            };

            let duration = start.elapsed();
            ToolDispatchResult::from_result(&tool_name, call_result, duration)
        })
    }
}

// ===================================================
// PermissionMiddleware
// ===================================================

/// Permission check function type.
pub type PermissionCheckFn = Arc<dyn Fn(&ToolDispatchContext) -> PermissionCheck + Send + Sync>;

/// Middleware that checks tool permissions before execution.
///
/// Inspects the [`PermissionCheck`] in the dispatch context. If the
/// permission is `Deny`, short-circuits with an error result. If
/// `Ask`, also denies (interactive prompts are outside the framework's
/// scope — agents should handle this themselves).
///
/// # Example
///
/// ```rust,ignore
/// // Deny all by default
/// let mw = PermissionMiddleware::deny_all();
///
/// // Custom logic
/// let mw = PermissionMiddleware::with_check(|ctx| {
///     if ctx.tool_name == "safe_read" {
///         PermissionCheck::Allow
///     } else {
///         PermissionCheck::Deny
///     }
/// });
/// ```
pub struct PermissionMiddleware {
    /// Override function for permission checking.
    ///
    /// When `Some`, this function is called to determine the permission
    /// for each dispatch. When `None`, the middleware reads
    /// [`ToolDispatchContext::permission`] directly.
    check_fn: Option<PermissionCheckFn>,
}

impl PermissionMiddleware {
    /// Create a permission middleware that denies all calls.
    ///
    /// Every tool call will be short-circuited with a permission-denied
    /// error. Useful as a safety default in restricted environments.
    #[must_use]
    pub fn deny_all() -> Self {
        Self {
            check_fn: Some(Arc::new(|_| PermissionCheck::Deny {
                reason: "blocked by policy".into(),
            })),
        }
    }

    /// Create a permission middleware that allows all calls.
    ///
    /// No permission checks are performed — every tool call passes
    /// through to the next layer. This is the runtime-equivalent of
    /// having no permission middleware at all, but it can be useful
    /// for logging or metrics in permissive environments.
    #[must_use]
    pub fn allow_all() -> Self {
        Self {
            check_fn: Some(Arc::new(|_| PermissionCheck::Allow)),
        }
    }

    /// Create a permission middleware with a custom check function.
    ///
    /// The function receives a reference to the dispatch context and
    /// returns the appropriate [`PermissionCheck`] for that call.
    pub fn with_check(
        f: impl Fn(&ToolDispatchContext) -> PermissionCheck + Send + Sync + 'static,
    ) -> Self {
        Self {
            check_fn: Some(Arc::new(f)),
        }
    }

    /// Create a permission middleware that reads from the context.
    ///
    /// The middleware reads `ctx.permission` directly, without
    /// applying any override. This is useful when the permission
    /// is set by the framework or a prior middleware.
    #[must_use]
    pub fn from_context() -> Self {
        Self { check_fn: None }
    }

    fn resolve_permission(&self, ctx: &ToolDispatchContext) -> PermissionCheck {
        match &self.check_fn {
            Some(f) => f(ctx),
            None => ctx.permission.clone(),
        }
    }
}

impl ToolMiddleware for PermissionMiddleware {
    fn name(&self) -> &'static str {
        "permission"
    }

    fn dispatch<'a>(
        &'a self,
        ctx: &'a mut ToolDispatchContext,
        next: &'a ToolPipeline,
    ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + 'a>> {
        let permission = self.resolve_permission(ctx);
        match permission {
            PermissionCheck::Allow => next.dispatch(ctx),
            PermissionCheck::Ask { .. } | PermissionCheck::Deny { .. } => {
                let tool_name = ctx.tool_name.clone();
                let reason = match &permission {
                    PermissionCheck::Deny { reason } => reason.clone(),
                    PermissionCheck::Ask { prompt } => format!("permission required: {prompt}"),
                    _ => "blocked".to_string(),
                };
                tracing::warn!(
                    tool = %tool_name,
                    permission = %reason,
                    "tool call blocked by permission middleware"
                );
                Box::pin(std::future::ready(ToolDispatchResult::err(
                    &tool_name,
                    format!("Permission {reason} for tool '{tool_name}'"),
                    Duration::ZERO,
                )))
            }
            PermissionCheck::Modify { .. } => {
                // Modify is treated as allow — the tool can proceed
                // but the agent might apply modifications to the input.
                next.dispatch(ctx)
            }
        }
    }
}

// ===================================================
// TimeoutMiddleware
// ===================================================

/// Configuration for the [`TimeoutMiddleware`].
#[derive(Debug, Clone)]
pub struct TimeoutConfig {
    /// Timeout for the initial tool execution attempt.
    ///
    /// If the inner dispatch does not complete within this duration,
    /// [`TimeoutMiddleware`] cancels the future and either retries
    /// (if [`retry_on_timeout`](TimeoutConfig::retry_on_timeout) is
    /// `true`) or returns a timeout error.
    pub timeout: Duration,

    /// Whether to retry once on timeout with double the timeout.
    ///
    /// When `true`, the middleware makes up to
    /// [`max_retries`](TimeoutConfig::max_retries) additional attempts,
    /// each with double the previous timeout.
    pub retry_on_timeout: bool,

    /// Maximum number of retries (0 = no retry, 1 = one retry).
    ///
    /// Each retry doubles the current timeout. The total number of
    /// attempts is `1 + max_retries`.
    pub max_retries: u32,
}

impl Default for TimeoutConfig {
    fn default() -> Self {
        Self {
            timeout: Duration::from_secs(120),
            retry_on_timeout: false,
            max_retries: 0,
        }
    }
}

/// Middleware that wraps tool execution in a timeout.
///
/// If the tool execution exceeds the configured timeout, returns an
/// error result. Optionally retries once with a longer timeout.
/// Respects the [`CancelSignal`] via `tokio::select!` so that
/// cancellation is not blocked by a slow tool.
///
/// # Example
///
/// ```rust,ignore
/// let mw = TimeoutMiddleware::from_secs(120);
/// let mw = TimeoutMiddleware::new(TimeoutConfig {
///     timeout: Duration::from_secs(60),
///     retry_on_timeout: false,
///     max_retries: 0,
/// });
/// ```
pub struct TimeoutMiddleware {
    config: TimeoutConfig,
}

impl TimeoutMiddleware {
    /// Create a timeout middleware with the given configuration.
    ///
    /// `config.timeout` controls the per-tool execution deadline.
    /// When `config.retry_on_timeout` is `true`, a timed-out call is
    /// retried up to `config.max_retries` additional times with an
    /// increasing back-off.
    ///
    /// For simpler construction see [`from_secs`](Self::from_secs) or
    /// [`none`](Self::none).
    #[must_use]
    pub fn new(config: TimeoutConfig) -> Self {
        Self { config }
    }

    /// Create a timeout middleware with a fixed timeout in seconds.
    ///
    /// Uses default retry settings (one retry with double timeout).
    #[must_use]
    pub fn from_secs(secs: u64) -> Self {
        Self {
            config: TimeoutConfig {
                timeout: Duration::from_secs(secs),
                ..TimeoutConfig::default()
            },
        }
    }

    /// Create a timeout middleware with no timeout (pass-through).
    ///
    /// Useful for testing or when timeouts are handled elsewhere.
    #[must_use]
    pub fn none() -> Self {
        Self {
            config: TimeoutConfig {
                timeout: Duration::MAX,
                retry_on_timeout: false,
                max_retries: 0,
            },
        }
    }
}

impl ToolMiddleware for TimeoutMiddleware {
    fn name(&self) -> &'static str {
        "timeout"
    }

    fn dispatch<'a>(
        &'a self,
        ctx: &'a mut ToolDispatchContext,
        next: &'a ToolPipeline,
    ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + 'a>> {
        let config = self.config.clone();
        let tool_name = ctx.tool_name.clone();
        let cancel = Arc::clone(&ctx.cancel);

        Box::pin(async move {
            let mut attempt = 0u32;
            let mut current_timeout = config.timeout;

            loop {
                let result_future = next.dispatch(ctx);
                let attempt_for_log = attempt;

                tokio::select! {
                    result = tokio::time::timeout(current_timeout, result_future) => {
                        if let Ok(dispatch_result) = result {
                            return dispatch_result;
                        }
                        attempt = attempt.saturating_add(1);
                        if config.retry_on_timeout && attempt <= config.max_retries {
                            tracing::warn!(
                                tool = %tool_name,
                                attempt = attempt_for_log,
                                timeout_secs = current_timeout.as_secs(),
                                "tool execution timed out, retrying"
                            );
                            current_timeout = current_timeout.saturating_mul(2);
                            continue;
                        }
                        tracing::error!(
                            tool = %tool_name,
                            timeout_secs = current_timeout.as_secs(),
                            "tool execution timed out"
                        );
                        return ToolDispatchResult::err(
                            &tool_name,
                            format!(
                                "Tool '{}' timed out after {}s",
                                tool_name,
                                current_timeout.as_secs()
                            ),
                            current_timeout,
                        );
                    }
                    () = cancel.notified() => {
                        return ToolDispatchResult::err(
                            &tool_name,
                            format!("Tool '{tool_name}' cancelled"),
                            Duration::ZERO,
                        );
                    }
                }
            }
        })
    }
}

// ===================================================
// UnknownToolMiddleware
// ===================================================

/// Middleware that suggests alternatives when a tool is not found.
///
/// This middleware wraps the core dispatch. When the inner dispatch
/// produces a "tool not found" error, this middleware intercepts it,
/// computes a string-similarity score against all registered tools,
/// and appends a suggestion to the error message.
///
/// # Similarity Metric
///
/// Uses a simple normalized longest-common-substring ratio. This is
/// fast and effective for the common case of minor typos (e.g.
/// `"bash"` → `"basj"`).
///
/// # Example
///
/// ```rust,ignore
/// let mw = UnknownToolMiddleware::new();
/// // If tool "basj" is not found, error message will say:
/// // "Tool 'basj' not found. Did you mean 'bash'?"
/// ```
pub struct UnknownToolMiddleware {
    /// The tool registry, used to enumerate available tool names
    /// for suggestions.
    ///
    /// Owned via `Arc` so the middleware can independently list
    /// tool names without needing to extract them from the chain.
    registry: Arc<ToolRegistry>,

    /// Minimum similarity score (0.0–1.0) to suggest an alternative.
    ///
    /// Only tools with a score at or above this threshold are suggested.
    /// Defaults to `0.4`.
    suggestion_threshold: f64,
}

impl UnknownToolMiddleware {
    /// Create a new unknown-tool middleware with default settings.
    ///
    /// Uses a [`suggestion_threshold`](Self::with_threshold) of `0.4`,
    /// which balances catching common typos against false-positive
    /// suggestions.
    ///
    /// For a custom threshold see [`with_threshold`](Self::with_threshold).
    #[must_use]
    pub fn new(registry: Arc<ToolRegistry>) -> Self {
        Self {
            registry,
            suggestion_threshold: 0.4,
        }
    }

    /// Create with a custom similarity threshold.
    ///
    /// Lower values produce more suggestions (more false positives).
    /// Higher values require closer matches.
    #[must_use]
    pub fn with_threshold(registry: Arc<ToolRegistry>, threshold: f64) -> Self {
        Self {
            registry,
            suggestion_threshold: threshold.clamp(0.0, 1.0),
        }
    }

    /// Compute similarity between two strings using a normalized
    /// longest-common-subsequence approach.
    ///
    /// Returns a value between 0.0 (completely different) and 1.0
    /// (identical).
    fn similarity(a: &str, b: &str) -> f64 {
        if a.is_empty() && b.is_empty() {
            return 1.0;
        }
        if a.is_empty() || b.is_empty() {
            return 0.0;
        }

        let a_lower = a.to_lowercase();
        let b_lower = b.to_lowercase();

        if a_lower == b_lower {
            return 1.0;
        }

        // Use longest common subsequence length as similarity metric
        let a_chars: Vec<char> = a_lower.chars().collect();
        let b_chars: Vec<char> = b_lower.chars().collect();
        let lcs_len = Self::lcs_length(&a_chars, &b_chars);

        // Tool names are short strings, so u32 is sufficient and avoids
        // usize→f64 precision loss on 64-bit targets.
        let max_len = u32::try_from(a_chars.len().max(b_chars.len())).unwrap_or(u32::MAX);
        let lcs_u32 = u32::try_from(lcs_len).unwrap_or(u32::MAX);

        // Check for prefix match bonus
        let prefix_len = a_chars
            .iter()
            .zip(b_chars.iter())
            .take_while(|(a, b)| a == b)
            .count();
        let prefix_bonus = if prefix_len > 0 {
            let p = u32::try_from(prefix_len).unwrap_or(u32::MAX);
            f64::from(p) / f64::from(max_len) * 0.1
        } else {
            0.0
        };

        f64::from(lcs_u32) / f64::from(max_len) + prefix_bonus
    }

    /// Compute the length of the longest common subsequence.
    /// Compute the length of the longest common subsequence of two character slices.
    ///
    /// Uses an iterative dynamic-programming approach with only two rows
    /// to keep memory usage O(min(a, b)).
    fn lcs_length(a: &[char], b: &[char]) -> usize {
        let mut prev = vec![0usize; b.len().saturating_add(1)];
        let mut curr = vec![0usize; b.len().saturating_add(1)];

        for &a_ch in a {
            for (j, &b_ch) in b.iter().enumerate() {
                let j_idx = j.saturating_add(1);
                *curr.get_mut(j_idx).unwrap_or(&mut 0) = if a_ch == b_ch {
                    prev.get(j_idx.saturating_sub(1))
                        .copied()
                        .unwrap_or(0)
                        .saturating_add(1)
                } else {
                    prev.get(j_idx)
                        .copied()
                        .unwrap_or(0)
                        .max(curr.get(j_idx.saturating_sub(1)).copied().unwrap_or(0))
                };
            }
            std::mem::swap(&mut prev, &mut curr);
            curr.fill(0);
        }

        *prev.get(b.len()).unwrap_or(&0)
    }

    /// Find the best matching tool name from a list, given a threshold.
    ///
    /// Returns the name with the highest similarity score that meets or
    /// exceeds `threshold`. Returns `None` when no candidate scores high
    /// enough.
    fn find_best_match_inner<'a>(
        requested: &str,
        available: &[&'a str],
        threshold: f64,
    ) -> Option<(&'a str, f64)> {
        let mut best: Option<(&'a str, f64)> = None;
        for &name in available {
            let score = Self::similarity(requested, name);
            if score >= threshold {
                match best {
                    Some((_, best_score)) if score <= best_score => {}
                    _ => best = Some((name, score)),
                }
            }
        }
        best
    }

    /// Check if a result looks like a "tool not found" error.
    ///
    /// Only considers single [`Text`](ToolContent::Text) results whose
    /// lowercased body contains `"not found"`.
    /// [`Multipart`](ToolContent::Multipart) results and non-error results
    /// always return `false`.
    fn is_tool_not_found(result: &ToolDispatchResult) -> bool {
        if !result.is_error {
            return false;
        }
        let msg = match &result.output {
            ToolContent::Text(t) => t.to_lowercase(),
            ToolContent::Multipart(_) => return false,
        };
        msg.contains("not found")
    }
}

impl ToolMiddleware for UnknownToolMiddleware {
    fn name(&self) -> &'static str {
        "unknown_tool"
    }

    fn dispatch<'a>(
        &'a self,
        ctx: &'a mut ToolDispatchContext,
        next: &'a ToolPipeline,
    ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + 'a>> {
        let tool_name = ctx.tool_name.clone();
        let registry_names = self.registry.tool_names();
        let threshold = self.suggestion_threshold;

        Box::pin(async move {
            let mut result = next.dispatch(ctx).await;

            if Self::is_tool_not_found(&result) {
                let available_refs: Vec<&str> = registry_names.iter().map(String::as_str).collect();

                if let Some((suggestion, score)) =
                    Self::find_best_match_inner(&tool_name, &available_refs, threshold)
                {
                    tracing::info!(
                        requested = %tool_name,
                        suggestion = %suggestion,
                        score = %score,
                        "suggesting alternative tool"
                    );
                    // Append suggestion to the error message
                    if let ToolContent::Text(ref mut msg) = result.output {
                        *msg = format!("{msg}. Did you mean '{suggestion}'?");
                    }
                }
            }

            result
        })
    }
}

// ===================================================
// OutputLimitMiddleware
// ===================================================

/// Middleware that truncates tool output to a maximum character count.
///
/// If the tool's text output exceeds the limit, it is truncated and
/// suffixed with a `[truncated]` marker. Non-text outputs ([`ToolContent::Multipart`])
/// are passed through unchanged.
///
/// This prevents runaway tools from flooding the conversation with
/// excessive output that would blow the context window.
///
/// # Example
///
/// ```rust,ignore
/// use loopctl::engine::middleware::OutputLimitMiddleware;
///
/// let pipeline = ToolPipeline::builder()
///     .with(OutputLimitMiddleware::new(10_000))
///     .core(registry)
///     .build()?;
/// ```
pub struct OutputLimitMiddleware {
    /// Maximum characters for text output.
    max_chars: usize,
}

impl OutputLimitMiddleware {
    /// Create a new output-limiting middleware.
    ///
    /// `max_chars` is the maximum number of characters in the text
    /// output. Outputs at or below this limit pass through unchanged.
    #[must_use]
    pub fn new(max_chars: usize) -> Self {
        Self { max_chars }
    }
}

impl ToolMiddleware for OutputLimitMiddleware {
    fn name(&self) -> &'static str {
        "output_limit"
    }

    fn dispatch<'a>(
        &'a self,
        ctx: &'a mut ToolDispatchContext,
        next: &'a ToolPipeline,
    ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + 'a>> {
        let max_chars = self.max_chars;
        Box::pin(async move {
            let mut result = next.dispatch(ctx).await;

            if let ToolContent::Text(ref text) = result.output {
                let char_count = text.chars().count();
                if char_count > max_chars {
                    let truncated: String = text.chars().take(max_chars).collect();
                    result.output = ToolContent::Text(format!("{truncated}\n[truncated]"));
                }
            }

            result
        })
    }
}

// ===================================================
// Tests
// ===================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::message::ToolContentPart;
    use crate::tool::{Tool, ToolContext, ToolError, ToolOutput, ToolSchema};
    use serde_json::json;
    use std::future::Future;
    use std::pin::Pin;
    use std::sync::atomic::{AtomicBool, Ordering};

    // ==================================================
    // Test tools
    // ==================================================

    /// A simple echo tool for testing.
    struct EchoTool;

    impl Tool for EchoTool {
        fn name(&self) -> &str {
            "echo"
        }
        fn description(&self) -> &str {
            "Echoes back the input"
        }
        fn schema(&self) -> ToolSchema {
            ToolSchema {
                tool: "echo".into(),
                description: "Echoes back the input".into(),
                input_schema: json!({
                    "type": "object",
                    "properties": { "message": { "type": "string" } },
                    "required": ["message"]
                }),
            }
        }
        fn call(
            &self,
            input: Value,
            _ctx: &ToolContext,
        ) -> Pin<Box<dyn Future<Output = Result<ToolOutput, ToolError>> + Send + '_>> {
            let msg = input["message"].as_str().unwrap_or("").to_string();
            Box::pin(async move { Ok(ToolOutput::text(msg)) })
        }
    }

    /// A tool that always errors.
    struct ErrorTool;

    impl Tool for ErrorTool {
        fn name(&self) -> &str {
            "error_tool"
        }
        fn description(&self) -> &str {
            "Always returns an error"
        }
        fn schema(&self) -> ToolSchema {
            ToolSchema {
                tool: "error_tool".into(),
                description: "Always returns an error".into(),
                input_schema: json!({"type": "object", "properties": {}}),
            }
        }
        fn call(
            &self,
            _input: Value,
            _ctx: &ToolContext,
        ) -> Pin<Box<dyn Future<Output = Result<ToolOutput, ToolError>> + Send + '_>> {
            Box::pin(async move { Err(ToolError::Execution("deliberate error".to_string())) })
        }
    }

    /// A slow tool for testing timeouts.
    struct SlowTool {
        delay_ms: u64,
    }

    impl Tool for SlowTool {
        fn name(&self) -> &str {
            "slow"
        }
        fn description(&self) -> &str {
            "Takes a long time"
        }
        fn schema(&self) -> ToolSchema {
            ToolSchema {
                tool: "slow".into(),
                description: "Takes a long time".into(),
                input_schema: json!({"type": "object", "properties": {}}),
            }
        }
        fn call(
            &self,
            _input: Value,
            _ctx: &ToolContext,
        ) -> Pin<Box<dyn Future<Output = Result<ToolOutput, ToolError>> + Send + '_>> {
            let delay = self.delay_ms;
            Box::pin(async move {
                tokio::time::sleep(Duration::from_millis(delay)).await;
                Ok(ToolOutput::text("finally done"))
            })
        }
    }

    // ==================================================
    // Helpers
    // ==================================================

    fn test_registry() -> Arc<ToolRegistry> {
        let mut reg = ToolRegistry::new();
        reg.register(EchoTool);
        reg.register(ErrorTool);
        reg.register(SlowTool { delay_ms: 5000 });
        Arc::new(reg)
    }

    fn test_ctx(name: &str) -> ToolDispatchContext {
        ToolDispatchContext {
            tool_name: name.to_string(),
            input: json!({ "message": "hello" }),
            call_id: "call_123".to_string(),
            turn_number: 1,
            cancel: Arc::new(CancelSignal::new()),
            permission: PermissionCheck::Allow,
            tool_context: ToolContext::default(),
        }
    }

    // ==================================================
    // Pipeline builder tests
    // ==================================================

    #[test]
    fn test_builder_requires_core() {
        let result = ToolPipeline::builder().build();
        assert!(result.is_err(), "should fail without core");
        match result {
            Err(PipelineError::MissingCore) => {}
            other => panic!("expected MissingCore, got {other:?}"),
        }
    }

    #[test]
    fn test_builder_succeeds_with_core() {
        let result = ToolPipeline::builder().core(test_registry()).build();
        assert!(result.is_ok());
    }

    #[test]
    fn test_pipeline_names_no_middleware() {
        let pipeline = ToolPipeline::builder()
            .core(test_registry())
            .build()
            .expect("valid");
        assert_eq!(pipeline.middleware_names(), vec!["tool_call"]);
    }

    #[test]
    fn test_pipeline_names_with_middleware() {
        let pipeline = ToolPipeline::builder()
            .with(PermissionMiddleware::allow_all())
            .with(TimeoutMiddleware::none())
            .core(test_registry())
            .build()
            .expect("valid");
        assert_eq!(
            pipeline.middleware_names(),
            vec!["permission", "timeout", "tool_call"]
        );
    }

    // ==================================================
    // Core dispatch tests
    // ==================================================

    #[tokio::test]
    async fn test_core_dispatch_echo() {
        let pipeline = ToolPipeline::new(test_registry());
        let result = pipeline.invoke(test_ctx("echo")).await;
        assert!(!result.is_error);
        assert_eq!(result.resolved_tool_name, "echo");
        match result.output {
            ToolContent::Text(ref t) => assert_eq!(t, "hello"),
            other => panic!("expected Text, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_core_dispatch_not_found() {
        let pipeline = ToolPipeline::new(test_registry());
        let result = pipeline.invoke(test_ctx("nonexistent")).await;
        assert!(result.is_error);
        assert_eq!(result.resolved_tool_name, "nonexistent");
        match result.output {
            ToolContent::Text(ref t) => assert!(t.contains("not found")),
            other => panic!("expected Text, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_core_dispatch_error_tool() {
        let pipeline = ToolPipeline::new(test_registry());
        let result = pipeline.invoke(test_ctx("error_tool")).await;
        assert!(result.is_error);
        assert_eq!(result.resolved_tool_name, "error_tool");
    }

    // ==================================================
    // PermissionMiddleware tests
    // ==================================================

    #[tokio::test]
    async fn test_permission_deny_all() {
        let pipeline = ToolPipeline::builder()
            .with(PermissionMiddleware::deny_all())
            .core(test_registry())
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("echo")).await;
        assert!(result.is_error);
        match result.output {
            ToolContent::Text(ref t) => assert!(
                t.contains("Permission") && t.contains("blocked"),
                "got: {t}"
            ),
            other => panic!("expected Text, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_permission_allow_all() {
        let pipeline = ToolPipeline::builder()
            .with(PermissionMiddleware::allow_all())
            .core(test_registry())
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("echo")).await;
        assert!(!result.is_error);
    }

    #[tokio::test]
    async fn test_permission_custom_check() {
        let pipeline = ToolPipeline::builder()
            .with(PermissionMiddleware::with_check(|ctx| {
                if ctx.tool_name == "echo" {
                    PermissionCheck::Allow
                } else {
                    PermissionCheck::Deny {
                        reason: "blocked".to_string(),
                    }
                }
            }))
            .core(test_registry())
            .build()
            .expect("valid");

        let echo_result = pipeline.invoke(test_ctx("echo")).await;
        assert!(!echo_result.is_error);

        let error_result = pipeline.invoke(test_ctx("error_tool")).await;
        assert!(error_result.is_error);
        match error_result.output {
            ToolContent::Text(ref t) => assert!(
                t.contains("Permission") && t.contains("blocked"),
                "got: {t}"
            ),
            other => panic!("expected Text, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_permission_from_context() {
        let mut ctx = test_ctx("echo");
        ctx.permission = PermissionCheck::Deny {
            reason: "test deny".to_string(),
        };

        let pipeline = ToolPipeline::builder()
            .with(PermissionMiddleware::from_context())
            .core(test_registry())
            .build()
            .expect("valid");

        let result = pipeline.invoke(ctx).await;
        assert!(result.is_error);
    }

    // ==================================================
    // TimeoutMiddleware tests
    // ==================================================

    #[tokio::test]
    async fn test_timeout_fast_tool_succeeds() {
        let registry = {
            let mut reg = ToolRegistry::new();
            reg.register(EchoTool);
            Arc::new(reg)
        };

        let pipeline = ToolPipeline::builder()
            .with(TimeoutMiddleware::from_secs(5))
            .core(registry)
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("echo")).await;
        assert!(!result.is_error);
    }

    #[tokio::test]
    async fn test_timeout_slow_tool_times_out() {
        let registry = {
            let mut reg = ToolRegistry::new();
            reg.register(SlowTool { delay_ms: 5000 });
            Arc::new(reg)
        };

        let pipeline = ToolPipeline::builder()
            .with(TimeoutMiddleware::new(TimeoutConfig {
                timeout: Duration::from_millis(50),
                retry_on_timeout: false,
                max_retries: 0,
            }))
            .core(registry)
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("slow")).await;
        assert!(result.is_error);
        match result.output {
            ToolContent::Text(ref t) => assert!(t.contains("timed out")),
            other => panic!("expected Text, got {other:?}"),
        }
    }

    // ==================================================
    // UnknownToolMiddleware tests
    // ==================================================

    #[test]
    fn test_similarity_identical() {
        let score = UnknownToolMiddleware::similarity("bash", "bash");
        assert!((score - 1.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_similarity_different() {
        let score = UnknownToolMiddleware::similarity("bash", "read_file");
        assert!(score < 0.5);
    }

    #[test]
    fn test_similarity_close() {
        let score = UnknownToolMiddleware::similarity("basj", "bash");
        assert!(score > 0.6, "expected close match, got {score}");
    }

    #[test]
    fn test_similarity_empty() {
        assert_eq!(UnknownToolMiddleware::similarity("", ""), 1.0);
        assert_eq!(UnknownToolMiddleware::similarity("a", ""), 0.0);
    }

    // ==================================================
    // dispatch_all tests
    // ==================================================

    #[tokio::test]
    async fn test_dispatch_all_sequential() {
        let pipeline = ToolPipeline::new(test_registry());

        let calls = vec![test_ctx("echo"), test_ctx("echo")];
        let results = pipeline.dispatch_all(calls).await.expect("should succeed");

        assert_eq!(results.len(), 2);
        for result in &results {
            assert!(!result.is_error);
        }
    }

    #[tokio::test]
    async fn test_dispatch_all_cancellation() {
        let cancel = Arc::new(CancelSignal::new());
        cancel.cancel();

        let mut ctx = test_ctx("echo");
        ctx.cancel = Arc::clone(&cancel);

        let pipeline = ToolPipeline::new(test_registry());
        let result = pipeline.dispatch_all(vec![ctx]).await;

        assert!(result.is_err());
    }

    // ==================================================
    // Ordering tests
    // ==================================================

    #[tokio::test]
    async fn test_middleware_ordering_permission_before_timeout() {
        // Permission denies → timeout middleware is never reached
        let registry = {
            let mut reg = ToolRegistry::new();
            reg.register(SlowTool { delay_ms: 5000 });
            Arc::new(reg)
        };

        let pipeline = ToolPipeline::builder()
            .with(PermissionMiddleware::deny_all())
            .with(TimeoutMiddleware::new(TimeoutConfig {
                timeout: Duration::from_millis(50),
                retry_on_timeout: false,
                max_retries: 0,
            }))
            .core(registry)
            .build()
            .expect("valid");

        let start = Instant::now();
        let result = pipeline.invoke(test_ctx("slow")).await;
        let elapsed = start.elapsed();

        assert!(result.is_error);
        // Should return immediately with permission denied, not wait for timeout
        assert!(
            elapsed < Duration::from_millis(200),
            "permission should short-circuit before timeout, took {:?}",
            elapsed
        );
        match result.output {
            ToolContent::Text(ref t) => assert!(
                t.contains("Permission") && t.contains("blocked"),
                "got: {t}"
            ),
            other => panic!("expected Text, got {other:?}"),
        }
    }

    // ==================================================
    // Integration: full pipeline
    // ==================================================

    #[tokio::test]
    async fn test_full_pipeline_echo() {
        let registry = {
            let mut reg = ToolRegistry::new();
            reg.register(EchoTool);
            Arc::new(reg)
        };

        let pipeline = ToolPipeline::builder()
            .with(PermissionMiddleware::allow_all())
            .with(TimeoutMiddleware::from_secs(30))
            .with(UnknownToolMiddleware::new(Arc::clone(&registry)))
            .core(registry)
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("echo")).await;
        assert!(!result.is_error);
        match result.output {
            ToolContent::Text(ref t) => assert_eq!(t, "hello"),
            other => panic!("expected Text, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_full_pipeline_not_found_with_suggestion() {
        let registry = {
            let mut reg = ToolRegistry::new();
            reg.register(EchoTool);
            reg.register(ErrorTool);
            Arc::new(reg)
        };

        let pipeline = ToolPipeline::builder()
            .with(PermissionMiddleware::allow_all())
            .with(UnknownToolMiddleware::with_threshold(
                Arc::clone(&registry),
                0.3,
            ))
            .core(registry)
            .build()
            .expect("valid");

        // "errr_tool" is close to "error_tool"
        let result = pipeline.invoke(test_ctx("errr_tool")).await;
        assert!(result.is_error);
        // Should now get a suggestion because the middleware has access to the registry
        match result.output {
            ToolContent::Text(ref msg) => {
                assert!(
                    msg.contains("Did you mean"),
                    "expected suggestion, got: {msg}"
                );
            }
            other => panic!("expected Text, got {other:?}"),
        }
    }

    // ==================================================
    // Short-circuit test
    // ==================================================

    /// A middleware that tracks whether it was reached.
    struct ReachTracker {
        reached: Arc<AtomicBool>,
    }

    impl ToolMiddleware for ReachTracker {
        fn name(&self) -> &str {
            "reach_tracker"
        }

        fn dispatch<'a>(
            &'a self,
            ctx: &'a mut ToolDispatchContext,
            next: &'a ToolPipeline,
        ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + 'a>> {
            self.reached.store(true, Ordering::SeqCst);
            next.dispatch(ctx)
        }
    }

    #[tokio::test]
    async fn test_permission_short_circuits_prevents_later_middleware() {
        let reached = Arc::new(AtomicBool::new(false));

        let pipeline = ToolPipeline::builder()
            .with(PermissionMiddleware::deny_all())
            .with(ReachTracker {
                reached: Arc::clone(&reached),
            })
            .core(test_registry())
            .build()
            .expect("valid");

        let _ = pipeline.invoke(test_ctx("echo")).await;
        assert!(
            !reached.load(Ordering::SeqCst),
            "middleware after deny should not be reached"
        );
    }

    // ===================================================
    // OutputLimitMiddleware tests
    // ===================================================

    /// A tool that returns a string of repeated characters for testing
    /// output truncation. The tool name encodes the repeat count as
    /// `long_output_N` where N is the number of characters.
    struct LongOutputTool;

    impl Tool for LongOutputTool {
        fn name(&self) -> &str {
            "long_output"
        }

        fn description(&self) -> &str {
            "Returns a long string for testing"
        }

        fn schema(&self) -> ToolSchema {
            ToolSchema {
                tool: self.name().to_string(),
                description: self.description().to_string(),
                input_schema: serde_json::json!({"type": "object", "properties": {}}),
            }
        }

        fn call(
            &self,
            input: Value,
            _ctx: &ToolContext,
        ) -> Pin<Box<dyn Future<Output = Result<ToolOutput, ToolError>> + Send + '_>> {
            Box::pin(async move {
                let count = input.get("count").and_then(|v| v.as_u64()).unwrap_or(100) as usize;
                let ch = input.get("char").and_then(|v| v.as_str()).unwrap_or("a");
                Ok(ToolOutput::text(ch.repeat(count)))
            })
        }
    }

    /// A tool that returns [`ToolContent::Multipart`] output for testing
    /// that non-text output passes through unchanged.
    struct MultipartTool;

    impl Tool for MultipartTool {
        fn name(&self) -> &str {
            "multipart"
        }

        fn description(&self) -> &str {
            "Returns multipart content"
        }

        fn schema(&self) -> ToolSchema {
            ToolSchema {
                tool: self.name().to_string(),
                description: self.description().to_string(),
                input_schema: serde_json::json!({"type": "object", "properties": {}}),
            }
        }

        fn call(
            &self,
            _input: Value,
            _ctx: &ToolContext,
        ) -> Pin<Box<dyn Future<Output = Result<ToolOutput, ToolError>> + Send + '_>> {
            Box::pin(async move {
                Ok(ToolOutput {
                    payload: ToolContent::Multipart(vec![
                        ToolContentPart::Text {
                            text: "part1".to_string(),
                        },
                        ToolContentPart::Text {
                            text: "part2".to_string(),
                        },
                    ]),
                    is_error: false,
                })
            })
        }
    }

    fn long_output_registry() -> Arc<ToolRegistry> {
        let mut registry = ToolRegistry::new();
        registry.register(LongOutputTool);
        registry.register(MultipartTool);
        Arc::new(registry)
    }

    fn long_output_ctx(tool_name: &str, count: usize) -> ToolDispatchContext {
        let mut ctx = test_ctx(tool_name);
        ctx.input = serde_json::json!({"count": count});
        ctx
    }

    #[tokio::test]
    async fn test_output_limit_short_text_passes_through() {
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with(OutputLimitMiddleware::new(1000))
            .core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", 50)).await;
        assert!(!result.is_error);
        assert_eq!(result.output, ToolContent::Text("a".repeat(50)));
    }

    #[tokio::test]
    async fn test_output_limit_exact_limit_passes_through() {
        let registry = long_output_registry();
        let limit = 100;
        let pipeline = ToolPipeline::builder()
            .with(OutputLimitMiddleware::new(limit))
            .core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", limit)).await;
        assert!(!result.is_error);
        assert_eq!(result.output, ToolContent::Text("a".repeat(limit)));
    }

    #[tokio::test]
    async fn test_output_limit_truncates_long_text() {
        let registry = long_output_registry();
        let limit = 50;
        let pipeline = ToolPipeline::builder()
            .with(OutputLimitMiddleware::new(limit))
            .core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", 200)).await;
        assert!(!result.is_error);
        let expected = format!("{}\n[truncated]", "a".repeat(limit));
        assert_eq!(result.output, ToolContent::Text(expected));
    }

    #[tokio::test]
    async fn test_output_limit_truncation_respects_char_boundary() {
        // Verify truncation operates on char boundaries, not bytes.
        let registry = long_output_registry();
        let limit = 5;
        let pipeline = ToolPipeline::builder()
            .with(OutputLimitMiddleware::new(limit))
            .core(Arc::clone(&registry))
            .build()
            .expect("valid");
        let mut ctx = test_ctx("long_output");
        ctx.input = serde_json::json!({"count": 10, "char": "é"});

        let result = pipeline.invoke(ctx).await;
        assert!(!result.is_error);
        let expected = format!("{}\n[truncated]", "é".repeat(limit));
        assert_eq!(result.output, ToolContent::Text(expected));
    }

    #[tokio::test]
    async fn test_output_limit_multipart_passes_through() {
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with(OutputLimitMiddleware::new(3))
            .core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("multipart")).await;
        assert!(!result.is_error);
        // Multipart content should pass through even though it exceeds
        // the character limit — truncation only applies to Text variant.
        assert!(
            matches!(result.output, ToolContent::Multipart(_)),
            "multipart should pass through unchanged"
        );
    }

    #[tokio::test]
    async fn test_output_limit_error_output_is_truncated() {
        // When a tool produces an error with a long message, the
        // OutputLimitMiddleware should still truncate it.
        let registry = test_registry(); // has EchoTool
        let pipeline = ToolPipeline::builder()
            .with(PermissionMiddleware::deny_all())
            .with(OutputLimitMiddleware::new(10))
            .core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("echo")).await;
        assert!(result.is_error);
        // Permission denied messages are short, so they may or may not
        // be truncated. The key assertion is that the pipeline ran both
        // middlewares without panicking.
    }

    #[tokio::test]
    async fn test_output_limit_preserves_duration() {
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with(OutputLimitMiddleware::new(10))
            .core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", 5000)).await;
        // Duration should reflect actual tool execution time, not be
        // zeroed out by the truncation middleware.
        assert!(
            result.duration > Duration::ZERO,
            "duration should be preserved after truncation"
        );
    }

    #[tokio::test]
    async fn test_output_limit_preserves_resolved_tool_name() {
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with(OutputLimitMiddleware::new(10))
            .core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", 500)).await;
        assert_eq!(result.resolved_tool_name, "long_output");
    }

    #[tokio::test]
    async fn test_output_limit_stacked_with_timeout() {
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with(TimeoutMiddleware::from_secs(120))
            .with(OutputLimitMiddleware::new(20))
            .core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", 1000)).await;
        assert!(!result.is_error);
        let expected = format!("{}\n[truncated]", "a".repeat(20));
        assert_eq!(result.output, ToolContent::Text(expected));
    }

    #[tokio::test]
    async fn test_output_limit_zero_chars_truncates_everything() {
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with(OutputLimitMiddleware::new(0))
            .core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", 100)).await;
        assert!(!result.is_error);
        assert_eq!(
            result.output,
            ToolContent::Text("\n[truncated]".to_string())
        );
    }

    /// Multi-byte UTF-8 text whose byte count exceeds `max_chars` but whose
    /// character count does **not** must pass through un-truncated.
    #[tokio::test]
    async fn test_output_limit_multibyte_under_char_limit_not_truncated() {
        // "日" is 3 bytes. 5 repetitions = 5 chars, 15 bytes.
        // Set max_chars = 8: 5 chars < 8, but 15 bytes > 8.
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with(OutputLimitMiddleware::new(8))
            .core(Arc::clone(&registry))
            .build()
            .expect("valid");
        let ctx = ToolDispatchContext {
            tool_name: "long_output".to_string(),
            input: json!({"count": 5, "char": "日"}),
            call_id: "mb-1".to_string(),
            turn_number: 1,
            cancel: Arc::new(CancelSignal::new()),
            permission: PermissionCheck::Allow,
            tool_context: ToolContext::default(),
        };

        let result = pipeline.invoke(ctx).await;
        assert!(!result.is_error);
        // Must NOT be truncated: 5 chars <= 8 max_chars, even though 15 bytes > 8.
        assert_eq!(result.output, ToolContent::Text("日日日日日".to_string()));
    }

    // ==================================================
    // ToolDispatchResult::from_result
    // ==================================================

    #[test]
    fn from_result_maps_ok_output() {
        let output = ToolOutput::text("hello");
        let result = ToolDispatchResult::from_result("echo", Ok(output), Duration::from_millis(50));
        assert!(!result.is_error);
        assert_eq!(result.output, ToolContent::Text("hello".to_string()));
        assert_eq!(result.resolved_tool_name, "echo");
        assert_eq!(result.duration, Duration::from_millis(50));
    }

    #[test]
    fn from_result_maps_err_to_error_result() {
        let error = ToolError::not_found("missing_tool", &[]);
        let result =
            ToolDispatchResult::from_result("missing_tool", Err(error), Duration::from_millis(10));
        assert!(result.is_error);
        assert_eq!(result.resolved_tool_name, "missing_tool");
    }

    // ==================================================
    // From<ToolOutput> + builder methods
    // ==================================================

    #[test]
    fn from_tool_output_defaults() {
        let output = ToolOutput::text("ok");
        let result = ToolDispatchResult::from(output);
        assert!(!result.is_error);
        assert_eq!(result.output, ToolContent::Text("ok".to_string()));
        assert_eq!(result.duration, Duration::ZERO);
        assert_eq!(result.resolved_tool_name, "");
    }

    #[test]
    fn from_tool_output_error_preserves_is_error() {
        let output = ToolOutput::error_text("boom");
        let result = ToolDispatchResult::from(output);
        assert!(result.is_error);
        assert_eq!(result.output, ToolContent::Text("boom".to_string()));
    }

    #[test]
    fn builder_methods_chain() {
        let output = ToolOutput::text("done");
        let result = ToolDispatchResult::from(output)
            .with_tool_name("bash")
            .with_duration(Duration::from_millis(99));
        assert_eq!(result.resolved_tool_name, "bash");
        assert_eq!(result.duration, Duration::from_millis(99));
        assert!(!result.is_error);
    }
}
