//! Tool dispatch middleware pipeline.
//!
//! Each middleware wraps the dispatch call and can inspect/modify the request before
//! execution and the result after execution.
//!
//! # Architecture
//!
//! ```text
//! [outer middleware .dispatch()]
//!   → pre-processing (inspect/modify context)
//!   → next.dispatch(ctx)
//!     → [inner middleware .dispatch()]
//!       → ...
//!       → [Innermost: ToolCallMiddleware → Tool::call()]
//!       → ...
//!   → post-processing (inspect/modify result)
//!   → return ToolDispatchResult
//! ```
//!
//! # Provided Middlewares
//!
//! | Middleware                | Description                                                       |
//! |---------------------------|-------------------------------------------------------------------|
//! | [`ToolCallMiddleware`]    | Innermost layer — looks up tool in registry, calls `Tool::call()` |
//! | [`PermissionMiddleware`]  | Checks [`PermissionCheck`] before execution                       |
//! | [`TimeoutMiddleware`]     | Wraps execution in a deadline with retry                          |
//! | [`UnknownToolMiddleware`] | Suggests closest matching tool on "not found"                     |
//! | [`RedactingMiddleware`]    | Scrubs secrets from output via a configurable pattern set         |
//! | [`SafetyShieldMiddleware`] | Enforces a tool-safety shield's Block decisions pre-dispatch       |
//! | [`OutputLimitMiddleware`] | Truncates output to a whole-output cap (floored at one marker)    |
//! | [`VerifyMiddleware`]      | Runs a verifier after write-class tools, appends the result       |
//! | [`MemoizingMiddleware`]   | Caches repeat calls keyed on `(tool_name, canonical input)`       |
//!
//! # Example
//!
//! ```rust,ignore
//! use loopctl::middleware::{
//!     ToolPipeline, ToolCallMiddleware, PermissionMiddleware, TimeoutMiddleware,
//! };
//! use loopctl::tool::ToolRegistry;
//! use std::sync::Arc;
//!
//! let registry = Arc::new(ToolRegistry::new());
//!
//! let pipeline = ToolPipeline::builder()
//!     .with_middleware(PermissionMiddleware::deny_all())
//!     .with_middleware(TimeoutMiddleware::from_secs(120))
//!     .with_core(registry)
//!     .build()
//!     .expect("pipeline configuration is valid");
//!
//! let result = pipeline.invoke(ctx).await;
//! ```

pub mod memoize;
pub mod output_limit;
pub mod permission;
#[cfg(feature = "redaction")]
pub mod redaction;
#[cfg(feature = "tool_shield")]
pub mod shield;
pub mod timeout;
pub mod tool_call;
pub mod unknown_tool;
pub mod verify;

use crate::cancel::CancelSignal;
use crate::error::LoopError;
use crate::tool::{PermissionCheck, ToolContext, ToolRegistry};
use serde_json::Value;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

pub use crate::tool::ToolDispatchResult;

pub use memoize::{MemoizingMiddleware, NoopPathExtractor, PathExtractor};
pub use output_limit::OutputLimitMiddleware;
pub use permission::{AskResolverFn, PermissionCheckFn, PermissionMiddleware};
#[cfg(feature = "redaction")]
pub use redaction::{RedactingMiddleware, SecretPattern, SecretPatternSet};
#[cfg(feature = "tool_shield")]
pub use shield::SafetyShieldMiddleware;
pub use timeout::{TimeoutConfig, TimeoutMiddleware};
pub use tool_call::ToolCallMiddleware;
pub use unknown_tool::UnknownToolMiddleware;
pub use verify::{NoopVerifier, Verifier, VerifyMiddleware, VerifyResult};

/// Context for a single tool invocation, passed through the middleware chain.
///
/// Built once per tool call by the framework, then threaded through each
/// middleware. Middlewares can read from and write to this struct.
///
/// Session identity is available via [`tool_context.session_id`](ToolContext::session_id)
/// rather than duplicated here.
pub struct ToolDispatchContext {
    /// The tool name from the model's tool call.
    ///
    /// Middlewares may rewrite this to redirect the call to a different tool
    /// (the rewritten name is what [`ToolCallMiddleware`] looks up).
    pub tool_name: String,

    /// The raw JSON input from the model.
    ///
    /// Middlewares can inspect or transform it before the tool runs — for
    /// example to scrub secrets, enforce limits, or fill defaults.
    pub input: Value,

    /// The call identifier generated by the model provider.
    ///
    /// Used to correlate each tool result back to the request that issued the
    /// call; forwarded onto [`ToolDispatchResult`] unchanged.
    pub call_id: String,

    /// The monotonically increasing turn counter for this session.
    ///
    /// Useful for per-turn limits (e.g. capping tool calls within a turn).
    pub turn_number: usize,

    /// The cancellation signal for this dispatch.
    ///
    /// Long-running middlewares (e.g. [`TimeoutMiddleware`]) should poll this
    /// via `tokio::select!` so a cancel aborts in-flight work promptly.
    pub cancel: Arc<CancelSignal>,

    /// The permission policy in effect for this call.
    ///
    /// Middlewares such as [`PermissionMiddleware`] read this to decide allow
    /// /deny and may modify it to escalate or restrict a subsequent decision.
    pub permission: PermissionCheck,

    /// The [`ToolContext`] passed to the eventual `Tool::call()`.
    ///
    /// Middlewares may augment it (add extensions, set fields) before
    /// [`ToolCallMiddleware`] invokes the tool.
    pub tool_context: ToolContext,
}

/// The trait for a middleware in the tool dispatch pipeline.
///
/// Each middleware wraps the "next" dispatch layer. The outermost middleware
/// is called first; it can pre-process the context, call `next.dispatch()`,
/// then post-process the result. Or it can short-circuit by returning a
/// result without calling `next`.
///
/// # Ordering Conventions
///
/// The typical registration order is:
///
/// 1. [`PermissionMiddleware`] — deny before any work is done
/// 2. [`TimeoutMiddleware`] — wrap execution in a deadline
/// 3. [`UnknownToolMiddleware`] — intercept "not found" errors
/// 4. (innermost) [`ToolCallMiddleware`] — the actual `Tool::call()`
///
/// Post-processing middlewares (e.g. output limiting) follow the same
/// rule: the first-registered middleware post-processes last, so an
/// output cap registered before everything else bounds whatever the
/// layers below it append to the result.
/// [`RedactingMiddleware`] prefers the
/// early slot for a related reason: registered outside the verifier, it
/// also scrubs what the layers below append — a verifier's diagnostics
/// can echo the secret the tool emitted — while a content-comparing
/// verifier registered outside it sees already-scrubbed text and may
/// misjudge it.
///
/// # Example
///
/// ```rust,ignore
/// struct LoggingMiddleware;
///
/// impl ToolMiddleware for LoggingMiddleware {
///     fn name(&self) -> &str { "logging" }
///
///     fn dispatch(
///         &self,
///         ctx: &mut ToolDispatchContext,
///         next: &ToolPipeline,
///     ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + '_>> {
///         Box::pin(async move {
///             tracing::info!("before tool: {}", ctx.tool_name);
///             let result = next.dispatch(ctx).await;
///             tracing::info!("after tool: {} (error={})", ctx.tool_name, result.is_error);
///             result
///         })
///     }
/// }
/// ```
pub trait ToolMiddleware: Send + Sync {
    /// Return a human-readable name for this middleware.
    ///
    /// Surfaced by [`ToolPipeline::middleware_names`] and used in logging,
    /// diagnostics, and error messages. Pick something stable and distinctive
    /// (e.g. `"permission"`, `"timeout"`) rather than a generated identifier.
    fn name(&self) -> &str;

    /// Process a single tool dispatch through this middleware layer.
    ///
    /// This is the heart of the middleware: pre-process `ctx`, then either call
    /// `next.dispatch(ctx)` to continue down the chain (and optionally
    /// post-process the returned [`ToolDispatchResult`]), or return a result
    /// directly to short-circuit the pipeline (e.g. deny a call before it
    /// reaches the tool).
    ///
    /// The returned future is pinned and boxed for object safety — implementors
    /// typically write `Box::pin(async move { … })`.
    fn dispatch<'a>(
        &'a self,
        ctx: &'a mut ToolDispatchContext,
        next: &'a ToolPipeline,
    ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + 'a>>;
}

/// Errors that can occur during pipeline construction.
///
/// Returned by [`ToolPipelineBuilder::build`] when the builder's state is not
/// sufficient to produce a runnable pipeline. Both variants are recoverable by
/// the caller: add the missing piece to the builder and rebuild.
#[derive(Debug, thiserror::Error)]
pub enum PipelineError {
    /// The pipeline has middleware layers but no core dispatch.
    ///
    /// Returned by [`build`](ToolPipelineBuilder::build) when at least one
    /// middleware was added via
    /// [`with_middleware`](ToolPipelineBuilder::with_middleware) but no tool
    /// registry was set via [`with_core`](ToolPipelineBuilder::with_core).
    /// Without a core, a middleware chain has nothing to dispatch into.
    ///
    /// Fix by calling `.with_core(registry)` before `.build()`.
    #[error("pipeline requires a core dispatch (call .with_core() with a ToolRegistry)")]
    MissingCore,

    /// The pipeline has nothing in it at all — no middleware and no core.
    ///
    /// Returned by [`build`](ToolPipelineBuilder::build) when neither
    /// [`with_middleware`](ToolPipelineBuilder::with_middleware) nor
    /// [`with_core`](ToolPipelineBuilder::with_core) was ever called. A
    /// completely empty pipeline cannot dispatch anything.
    ///
    /// Fix by adding at least a core: `.with_core(registry)`. (For the common
    /// case of "no middleware, just the registry," prefer the shortcut
    /// [`ToolPipeline::new`].)
    #[error("pipeline has no middlewares and no core dispatch")]
    Empty,
}

/// An assembled, immutable middleware pipeline for tool dispatch.
///
/// Holds an ordered list of [`ToolMiddleware`] layers wrapped around an
/// innermost [`ToolCallMiddleware`], which performs the actual tool lookup and
/// `Tool::call()` invocation against a [`ToolRegistry`]. Once built, a pipeline
/// does not change: the middleware list and core are both held behind [`Arc`],
/// so a pipeline is cheap to share across tasks and threads.
///
/// # The cursor model
///
/// Rather than threading a separate "next" pointer through each layer, the
/// pipeline carries an internal `index` cursor. Entry starts at index 0; each
/// middleware receives a pipeline advanced by one position as its `next`
/// argument, and when the cursor runs off the end of the middleware list it
/// falls through to the core. Constructing those one-step-advanced views costs
/// only `Arc` clones (no middleware is copied), so the design stays allocation
/// -light per dispatch.
///
/// # Construction
///
/// Use [`builder`](Self::builder) to get a [`ToolPipelineBuilder`], add
/// middleware layers with
/// [`with_middleware`](ToolPipelineBuilder::with_middleware), set the core
/// registry with [`with_core`](ToolPipelineBuilder::with_core), and finalize
/// with [`build`](ToolPipelineBuilder::build). For the zero-middleware case,
/// [`new`](Self::new) is a shortcut.
///
/// # Dispatch
///
/// - [`invoke`](Self::invoke) — the public entry point: run one tool call
///   through the full chain from index 0.
/// - [`dispatch_all`](Self::dispatch_all) — run several calls in sequence,
///   checking cancellation between them.
/// - [`dispatch`](Self::dispatch) — the internal, cursor-aware step used by
///   middlewares to continue the chain. Callers normally use `invoke`.
///
/// # Example
///
/// ```rust,ignore
/// let pipeline = ToolPipeline::builder()
///     .with_middleware(PermissionMiddleware::deny_all())
///     .with_middleware(TimeoutMiddleware::from_secs(120))
///     .with_core(registry)
///     .build()
///     .expect("pipeline configuration is valid");
///
/// let result = pipeline.invoke(ctx).await;
/// ```
pub struct ToolPipeline {
    /// The middleware layers in execution order — index 0 is the outermost
    /// (runs its pre-processing first, post-processing last). Held in an
    /// `Arc<[…]>` so advancing the cursor only clones the shared slice.
    middlewares: Arc<[Arc<dyn ToolMiddleware>]>,

    /// The innermost dispatch layer, built from the [`ToolRegistry`] at
    /// [`build`](ToolPipelineBuilder::build) time and wrapped in a
    /// [`ToolCallMiddleware`]. Reached once the cursor passes the last
    /// middleware: it performs the actual `Tool::call()`.
    core: Arc<ToolCallMiddleware>,

    /// The cursor into `middlewares`: `0` at the chain entry, incremented by
    /// one for each `next` view handed to a middleware. Past-the-end means
    /// "delegate to `core`".
    index: usize,
}

impl std::fmt::Debug for ToolPipeline {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ToolPipeline")
            .field("middleware_count", &self.middlewares.len())
            .field("middleware_names", &self.middleware_names())
            .finish_non_exhaustive()
    }
}

impl ToolPipeline {
    /// Create a new pipeline builder for fluent configuration.
    ///
    /// Returns a [`ToolPipelineBuilder`] starting with no middleware layers.
    /// Add layers with
    /// [`with_middleware`](ToolPipelineBuilder::with_middleware), set the core
    /// with [`with_core`](ToolPipelineBuilder::with_core), then
    /// [`build`](ToolPipelineBuilder::build).
    ///
    /// Prefer this over [`new`](Self::new) whenever you want any middleware at
    /// all; `new` is the shortcut for the zero-middleware case.
    #[must_use]
    pub fn builder() -> ToolPipelineBuilder {
        ToolPipelineBuilder::new()
    }

    /// Create a minimal pipeline with only the core dispatch and no middleware.
    ///
    /// Equivalent to `ToolPipeline::builder().with_core(registry).build()` with
    /// the core guaranteed present. Useful for cases where no middleware is
    /// needed (e.g. tests, or a host app that wants raw `Tool::call()` with no
    /// wrapping). To add layers, use [`builder`](Self::builder) instead.
    #[must_use]
    pub fn new(registry: Arc<ToolRegistry>) -> Self {
        Self {
            middlewares: Arc::new([]),
            core: Arc::new(ToolCallMiddleware::new(registry)),
            index: 0,
        }
    }

    /// Dispatch to the middleware layer at the current cursor index.
    ///
    /// This is the internal step that walks the chain. If [`index`](Self) points
    /// at a middleware, that middleware's [`dispatch`](ToolMiddleware::dispatch)
    /// runs, receiving a one-step-advanced copy of the pipeline as its `next`
    /// argument so it can continue the chain by calling `next.dispatch(ctx)`.
    /// Once the cursor advances past the last middleware, the call falls
    /// through to the core [`ToolCallMiddleware`], which performs the actual
    /// `Tool::call()`.
    ///
    /// Callers outside the middleware trait usually want [`invoke`](Self::invoke)
    /// (which starts a fresh dispatch at index 0) rather than this method.
    /// This method is `pub` because middlewares receive a `&ToolPipeline` and
    /// must be able to advance it.
    pub fn dispatch<'a>(
        &'a self,
        ctx: &'a mut ToolDispatchContext,
    ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + 'a>> {
        let Some(middleware) = self.middlewares.get(self.index).cloned() else {
            let core = Arc::clone(&self.core);
            return Box::pin(async move { core.dispatch(ctx).await });
        };
        let next = ToolPipeline {
            middlewares: Arc::clone(&self.middlewares),
            core: Arc::clone(&self.core),
            index: self.index.saturating_add(1),
        };
        Box::pin(async move { middleware.dispatch(ctx, &next).await })
    }

    /// Run one tool call through the full pipeline from the start.
    ///
    /// This is the public entry point for dispatch. It builds a fresh root view
    /// of the pipeline at `index` 0 and drives it to completion, so it is safe
    /// to call on any pipeline — including a `next` view a middleware received
    /// mid-chain — without that view's advanced cursor affecting the result.
    /// Building the root view costs two `Arc` clones (the middleware slice and
    /// the core), which is negligible relative to a tool call.
    ///
    /// To run several calls with cancellation checked between them, use
    /// [`dispatch_all`](Self::dispatch_all).
    pub async fn invoke(&self, mut ctx: ToolDispatchContext) -> ToolDispatchResult {
        let root = ToolPipeline {
            middlewares: Arc::clone(&self.middlewares),
            core: Arc::clone(&self.core),
            index: 0,
        };
        root.dispatch(&mut ctx).await
    }

    /// Dispatch multiple tool calls sequentially, in input order.
    ///
    /// Each call independently traverses the full middleware chain via
    /// [`invoke`](Self::invoke). The cancellation signal is checked before
    /// every call and again after each one returns; if it is ever set, the
    /// remaining calls are skipped and the error is returned immediately. Note
    /// that any results produced before the cancellation are discarded — this
    /// returns either all results or an error, never a partial batch.
    ///
    /// Results come back in the same order as the input calls.
    ///
    /// # Errors
    ///
    /// Returns [`LoopError::Cancelled`] if the cancellation signal is set at
    /// any check point before all calls have completed.
    pub async fn dispatch_all(
        &self,
        calls: Vec<ToolDispatchContext>,
    ) -> Result<Vec<ToolDispatchResult>, LoopError> {
        let mut results = Vec::with_capacity(calls.len());
        for ctx in calls {
            if ctx.cancel.is_cancelled() {
                return Err(LoopError::Cancelled);
            }
            let cancel = Arc::clone(&ctx.cancel);
            let result = self.invoke(ctx).await;
            if cancel.is_cancelled() {
                return Err(LoopError::Cancelled);
            }
            results.push(result);
        }
        Ok(results)
    }

    /// Return the names of all middleware layers in execution order.
    ///
    /// Includes the core [`ToolCallMiddleware`] as the final entry. Useful for
    /// diagnostics, logging, and asserting pipeline composition in tests.
    #[must_use]
    pub fn middleware_names(&self) -> Vec<&str> {
        let mut names: Vec<&str> = self.middlewares.iter().map(|m| m.name()).collect();
        names.push(ToolCallMiddleware::NAME);
        names
    }
}

/// Builds an ordered middleware pipeline for tool dispatch.
///
/// # Example
///
/// ```rust,ignore
/// let pipeline = ToolPipeline::builder()
///     .with_middleware(PermissionMiddleware::deny_all())
///     .with_middleware(TimeoutMiddleware::from_secs(120))
///     .with_core(Arc::new(tool_registry))
///     .build()
///     .expect("pipeline configuration is valid");
/// ```
pub struct ToolPipelineBuilder {
    middlewares: Vec<Arc<dyn ToolMiddleware>>,
    core: Option<Arc<ToolRegistry>>,
}

impl ToolPipelineBuilder {
    /// Create a new, empty builder.
    ///
    /// Start here, then chain [`with_middleware`](Self::with_middleware) calls
    /// to add layers, finish with [`with_core`](Self::with_core) to set the
    /// registry, and call [`build`](Self::build) to finalize.
    #[must_use]
    pub fn new() -> Self {
        Self {
            middlewares: Vec::new(),
            core: None,
        }
    }

    /// Append a middleware layer to the pipeline.
    ///
    /// Layers execute in the order they are added: the first call becomes the
    /// outermost wrapper (its pre-processing runs before everything else, its
    /// post-processing runs last). The core dispatch registered via
    /// [`with_core`](Self::with_core) is always the innermost layer.
    ///
    /// The middleware is boxed into an [`Arc`] internally, so each call moves
    /// a distinct owned instance into the pipeline. To share one instance
    /// across multiple pipelines, use
    /// [`with_middleware_arc`](Self::with_middleware_arc).
    #[must_use]
    pub fn with_middleware<M: ToolMiddleware + 'static>(mut self, middleware: M) -> Self {
        self.middlewares.push(Arc::new(middleware));
        self
    }

    /// Append an already-`Arc`-wrapped middleware.
    ///
    /// Like [`with_middleware`](Self::with_middleware) but takes a pre-wrapped
    /// [`Arc<dyn ToolMiddleware>`]. Use this when the same middleware instance
    /// must be shared across multiple pipelines: by passing the `Arc` in,
    /// every pipeline that receives it observes the same underlying state
    /// (rather than each getting its own owned copy as `with_middleware` would).
    #[must_use]
    pub fn with_middleware_arc(mut self, middleware: Arc<dyn ToolMiddleware>) -> Self {
        self.middlewares.push(middleware);
        self
    }

    /// Set the core tool registry the pipeline dispatches into.
    ///
    /// The registry is wrapped in a [`ToolCallMiddleware`] that performs the
    /// actual tool lookup and `Tool::call()` invocation — this is always the
    /// innermost layer of the pipeline, reached after every registered
    /// middleware has run its pre-processing. A pipeline without a core cannot
    /// be built (see [`build`](Self::build)).
    #[must_use]
    pub fn with_core(mut self, registry: Arc<ToolRegistry>) -> Self {
        self.core = Some(registry);
        self
    }

    /// Finalize the builder into an assembled [`ToolPipeline`].
    ///
    /// Freezes the middleware order and wraps the core registry in a
    /// [`ToolCallMiddleware`]. The returned pipeline is ready to
    /// [`invoke`](ToolPipeline::invoke).
    ///
    /// # Errors
    ///
    /// - [`PipelineError::Empty`] if neither middleware nor a core registry
    ///   was added — the builder is untouched.
    /// - [`PipelineError::MissingCore`] if at least one middleware was added
    ///   but no core registry was set via [`with_core`](Self::with_core). A
    ///   middleware chain needs somewhere to dispatch.
    pub fn build(self) -> Result<ToolPipeline, PipelineError> {
        let Some(registry) = self.core else {
            return Err(if self.middlewares.is_empty() {
                PipelineError::Empty
            } else {
                PipelineError::MissingCore
            });
        };
        Ok(ToolPipeline {
            middlewares: self.middlewares.into(),
            core: Arc::new(ToolCallMiddleware::new(registry)),
            index: 0,
        })
    }
}

impl Default for ToolPipelineBuilder {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cancel::CancelSignal;
    use crate::message::ToolContent;
    use crate::message::ToolContentPart;
    use crate::tool::{PermissionCheck, Tool, ToolContext, ToolError, ToolOutput, ToolSchema};
    use serde_json::json;
    use std::future::Future;
    use std::pin::Pin;
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::time::{Duration, Instant};

    struct EchoTool;

    impl Tool for EchoTool {
        fn name(&self) -> &'static str {
            "echo"
        }
        fn description(&self) -> &'static str {
            "Echoes back the input"
        }
        fn schema(&self) -> ToolSchema {
            ToolSchema {
                tool: "echo".into(),
                description: "Echoes back the input".into(),
                input_schema: json!({
                    "type": "object",
                    "properties": { "message": { "type": "string" } },
                    "required": ["message"]
                }),
            }
        }
        fn call(
            &self,
            input: Value,
            _ctx: &ToolContext,
        ) -> Pin<Box<dyn Future<Output = Result<ToolOutput, ToolError>> + Send + '_>> {
            let msg = input["message"].as_str().unwrap_or("").to_string();
            Box::pin(async move { Ok(ToolOutput::text(msg)) })
        }
    }

    struct ErrorTool;

    impl Tool for ErrorTool {
        fn name(&self) -> &'static str {
            "error_tool"
        }
        fn description(&self) -> &'static str {
            "Always returns an error"
        }
        fn schema(&self) -> ToolSchema {
            ToolSchema {
                tool: "error_tool".into(),
                description: "Always returns an error".into(),
                input_schema: json!({"type": "object", "properties": {}}),
            }
        }
        fn call(
            &self,
            _input: Value,
            _ctx: &ToolContext,
        ) -> Pin<Box<dyn Future<Output = Result<ToolOutput, ToolError>> + Send + '_>> {
            Box::pin(async move { Err(ToolError::Execution("deliberate error".to_string())) })
        }
    }

    struct SlowTool {
        delay_ms: u64,
    }

    impl Tool for SlowTool {
        fn name(&self) -> &'static str {
            "slow"
        }
        fn description(&self) -> &'static str {
            "Takes a long time"
        }
        fn schema(&self) -> ToolSchema {
            ToolSchema {
                tool: "slow".into(),
                description: "Takes a long time".into(),
                input_schema: json!({"type": "object", "properties": {}}),
            }
        }
        fn call(
            &self,
            _input: Value,
            _ctx: &ToolContext,
        ) -> Pin<Box<dyn Future<Output = Result<ToolOutput, ToolError>> + Send + '_>> {
            let delay = self.delay_ms;
            Box::pin(async move {
                tokio::time::sleep(Duration::from_millis(delay)).await;
                Ok(ToolOutput::text("finally done"))
            })
        }
    }

    fn test_registry() -> Arc<ToolRegistry> {
        let mut reg = ToolRegistry::new();
        reg.register(EchoTool);
        reg.register(ErrorTool);
        reg.register(SlowTool { delay_ms: 5000 });
        Arc::new(reg)
    }

    fn test_ctx(name: &str) -> ToolDispatchContext {
        ToolDispatchContext {
            tool_name: name.to_string(),
            input: json!({ "message": "hello" }),
            call_id: "call_123".to_string(),
            turn_number: 1,
            cancel: Arc::new(CancelSignal::new()),
            permission: PermissionCheck::Allow,
            tool_context: ToolContext::default(),
        }
    }

    #[test]
    fn test_builder_empty_is_empty_error() {
        // No middleware and no core -> Empty (not MissingCore).
        let result = ToolPipeline::builder().build();
        match result {
            Err(PipelineError::Empty) => {}
            other => panic!("expected Empty for an untouched builder, got {other:?}"),
        }
    }

    #[test]
    fn test_builder_middleware_without_core_is_missing_core() {
        // Middleware added but no core -> MissingCore (distinct from Empty).
        let result = ToolPipeline::builder()
            .with_middleware(TimeoutMiddleware::none())
            .build();
        match result {
            Err(PipelineError::MissingCore) => {}
            other => panic!("expected MissingCore, got {other:?}"),
        }
    }

    #[test]
    fn test_builder_succeeds_with_core() {
        let result = ToolPipeline::builder().with_core(test_registry()).build();
        assert!(result.is_ok());
    }

    #[test]
    fn test_pipeline_names_no_middleware() {
        let pipeline = ToolPipeline::builder()
            .with_core(test_registry())
            .build()
            .expect("valid");
        assert_eq!(pipeline.middleware_names(), vec!["tool_call"]);
    }

    #[test]
    fn test_pipeline_names_with_middleware() {
        let pipeline = ToolPipeline::builder()
            .with_middleware(PermissionMiddleware::allow_all())
            .with_middleware(TimeoutMiddleware::none())
            .with_core(test_registry())
            .build()
            .expect("valid");
        assert_eq!(
            pipeline.middleware_names(),
            vec!["permission", "timeout", "tool_call"]
        );
    }

    #[tokio::test]
    async fn test_core_dispatch_echo() {
        let pipeline = ToolPipeline::new(test_registry());
        let result = pipeline.invoke(test_ctx("echo")).await;
        assert!(!result.is_error);
        assert_eq!(result.resolved_tool_name, "echo");
        match result.output {
            ToolContent::Text(ref t) => assert_eq!(t, "hello"),
            other @ ToolContent::Multipart(_) => panic!("expected Text, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_core_dispatch_not_found() {
        let pipeline = ToolPipeline::new(test_registry());
        let result = pipeline.invoke(test_ctx("nonexistent")).await;
        assert!(result.is_error);
        assert_eq!(result.resolved_tool_name, "nonexistent");
        match result.output {
            ToolContent::Text(ref t) => assert!(t.contains("not found")),
            other @ ToolContent::Multipart(_) => panic!("expected Text, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_core_dispatch_error_tool() {
        let pipeline = ToolPipeline::new(test_registry());
        let result = pipeline.invoke(test_ctx("error_tool")).await;
        assert!(result.is_error);
        assert_eq!(result.resolved_tool_name, "error_tool");
    }

    #[tokio::test]
    async fn test_permission_deny_all() {
        let pipeline = ToolPipeline::builder()
            .with_middleware(PermissionMiddleware::deny_all())
            .with_core(test_registry())
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("echo")).await;
        assert!(result.is_error);
        match result.output {
            ToolContent::Text(ref t) => assert!(
                t.contains("Permission") && t.contains("blocked"),
                "got: {t}"
            ),
            other @ ToolContent::Multipart(_) => panic!("expected Text, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_permission_allow_all() {
        let pipeline = ToolPipeline::builder()
            .with_middleware(PermissionMiddleware::allow_all())
            .with_core(test_registry())
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("echo")).await;
        assert!(!result.is_error);
    }

    #[tokio::test]
    async fn test_permission_custom_check() {
        let pipeline = ToolPipeline::builder()
            .with_middleware(PermissionMiddleware::from_context().with_check(|ctx| {
                if ctx.tool_name == "echo" {
                    PermissionCheck::Allow
                } else {
                    PermissionCheck::Deny {
                        reason: "blocked".to_string(),
                    }
                }
            }))
            .with_core(test_registry())
            .build()
            .expect("valid");

        let echo_result = pipeline.invoke(test_ctx("echo")).await;
        assert!(!echo_result.is_error);

        let error_result = pipeline.invoke(test_ctx("error_tool")).await;
        assert!(error_result.is_error);
        match error_result.output {
            ToolContent::Text(ref t) => assert!(
                t.contains("Permission") && t.contains("blocked"),
                "got: {t}"
            ),
            other @ ToolContent::Multipart(_) => panic!("expected Text, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_permission_from_context() {
        let mut ctx = test_ctx("echo");
        ctx.permission = PermissionCheck::Deny {
            reason: "test deny".to_string(),
        };

        let pipeline = ToolPipeline::builder()
            .with_middleware(PermissionMiddleware::from_context())
            .with_core(test_registry())
            .build()
            .expect("valid");

        let result = pipeline.invoke(ctx).await;
        assert!(result.is_error);
    }

    #[tokio::test]
    async fn test_permission_ask_without_resolver_denies() {
        let mut ctx = test_ctx("echo");
        ctx.permission = PermissionCheck::Ask {
            prompt: "Allow echo?".to_string(),
        };

        // from_context() has no ask_resolver configured.
        let pipeline = ToolPipeline::builder()
            .with_middleware(PermissionMiddleware::from_context())
            .with_core(test_registry())
            .build()
            .expect("valid");

        let result = pipeline.invoke(ctx).await;
        assert!(
            result.is_error,
            "Ask without resolver should deny the tool call"
        );
        let msg = result.output.to_string();
        assert!(
            msg.contains("permission"),
            "error should mention permission: {msg}"
        );
    }

    #[tokio::test]
    async fn test_timeout_fast_tool_succeeds() {
        let registry = {
            let mut reg = ToolRegistry::new();
            reg.register(EchoTool);
            Arc::new(reg)
        };

        let pipeline = ToolPipeline::builder()
            .with_middleware(TimeoutMiddleware::from_secs(5))
            .with_core(registry)
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("echo")).await;
        assert!(!result.is_error);
    }

    #[tokio::test]
    async fn test_timeout_slow_tool_times_out() {
        let registry = {
            let mut reg = ToolRegistry::new();
            reg.register(SlowTool { delay_ms: 5000 });
            Arc::new(reg)
        };

        let pipeline = ToolPipeline::builder()
            .with_middleware(TimeoutMiddleware::new(TimeoutConfig {
                timeout: Duration::from_millis(50),
                retry_on_timeout: false,
                max_retries: 0,
            }))
            .with_core(registry)
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("slow")).await;
        assert!(result.is_error);
        match result.output {
            ToolContent::Text(ref t) => assert!(t.contains("timed out")),
            other @ ToolContent::Multipart(_) => panic!("expected Text, got {other:?}"),
        }
    }

    #[test]
    fn test_similarity_identical() {
        let score = UnknownToolMiddleware::similarity("bash", "bash");
        assert!((score - 1.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_similarity_different() {
        let score = UnknownToolMiddleware::similarity("bash", "read_file");
        assert!(score < 0.5);
    }

    #[test]
    fn test_similarity_close() {
        let score = UnknownToolMiddleware::similarity("basj", "bash");
        assert!(score > 0.6, "expected close match, got {score}");
    }

    #[test]
    fn test_similarity_empty() {
        assert!((UnknownToolMiddleware::similarity("", "") - 1.0).abs() < f64::EPSILON);
        assert!((UnknownToolMiddleware::similarity("a", "") - 0.0).abs() < f64::EPSILON);
    }

    #[tokio::test]
    async fn test_dispatch_all_sequential() {
        let pipeline = ToolPipeline::new(test_registry());

        let calls = vec![test_ctx("echo"), test_ctx("echo")];
        let results = pipeline.dispatch_all(calls).await.expect("should succeed");

        assert_eq!(results.len(), 2);
        for result in &results {
            assert!(!result.is_error);
        }
    }

    #[tokio::test]
    async fn test_dispatch_all_cancellation() {
        let cancel = Arc::new(CancelSignal::new());
        cancel.cancel();

        let mut ctx = test_ctx("echo");
        ctx.cancel = Arc::clone(&cancel);

        let pipeline = ToolPipeline::new(test_registry());
        let result = pipeline.dispatch_all(vec![ctx]).await;

        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_middleware_ordering_permission_before_timeout() {
        // Permission denies → timeout middleware is never reached
        let registry = {
            let mut reg = ToolRegistry::new();
            reg.register(SlowTool { delay_ms: 5000 });
            Arc::new(reg)
        };

        let pipeline = ToolPipeline::builder()
            .with_middleware(PermissionMiddleware::deny_all())
            .with_middleware(TimeoutMiddleware::new(TimeoutConfig {
                timeout: Duration::from_millis(50),
                retry_on_timeout: false,
                max_retries: 0,
            }))
            .with_core(registry)
            .build()
            .expect("valid");

        let start = Instant::now();
        let result = pipeline.invoke(test_ctx("slow")).await;
        let elapsed = start.elapsed();

        assert!(result.is_error);
        // Should return immediately with permission denied, not wait for timeout
        assert!(
            elapsed < Duration::from_millis(200),
            "permission should short-circuit before timeout, took {elapsed:?}",
        );
        match result.output {
            ToolContent::Text(ref t) => assert!(
                t.contains("Permission") && t.contains("blocked"),
                "got: {t}"
            ),
            other @ ToolContent::Multipart(_) => panic!("expected Text, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_full_pipeline_echo() {
        let registry = {
            let mut reg = ToolRegistry::new();
            reg.register(EchoTool);
            Arc::new(reg)
        };

        let pipeline = ToolPipeline::builder()
            .with_middleware(PermissionMiddleware::allow_all())
            .with_middleware(TimeoutMiddleware::from_secs(30))
            .with_middleware(UnknownToolMiddleware::new(Arc::clone(&registry)))
            .with_core(registry)
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("echo")).await;
        assert!(!result.is_error);
        match result.output {
            ToolContent::Text(ref t) => assert_eq!(t, "hello"),
            other @ ToolContent::Multipart(_) => panic!("expected Text, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_full_pipeline_not_found_with_suggestion() {
        let registry = {
            let mut reg = ToolRegistry::new();
            reg.register(EchoTool);
            reg.register(ErrorTool);
            Arc::new(reg)
        };

        let pipeline = ToolPipeline::builder()
            .with_middleware(PermissionMiddleware::allow_all())
            .with_middleware(UnknownToolMiddleware::new(Arc::clone(&registry)).with_threshold(0.3))
            .with_core(registry)
            .build()
            .expect("valid");

        // "errr_tool" is close to "error_tool"
        let result = pipeline.invoke(test_ctx("errr_tool")).await;
        assert!(result.is_error);
        // Should now get a suggestion because the middleware has access to the registry
        match result.output {
            ToolContent::Text(ref msg) => {
                assert!(
                    msg.contains("Did you mean"),
                    "expected suggestion, got: {msg}"
                );
            }
            other @ ToolContent::Multipart(_) => panic!("expected Text, got {other:?}"),
        }
    }

    struct ReachTracker {
        reached: Arc<AtomicBool>,
    }

    impl ToolMiddleware for ReachTracker {
        fn name(&self) -> &'static str {
            "reach_tracker"
        }

        fn dispatch<'a>(
            &'a self,
            ctx: &'a mut ToolDispatchContext,
            next: &'a ToolPipeline,
        ) -> Pin<Box<dyn Future<Output = ToolDispatchResult> + Send + 'a>> {
            self.reached.store(true, Ordering::SeqCst);
            next.dispatch(ctx)
        }
    }

    #[tokio::test]
    async fn test_permission_short_circuits_prevents_later_middleware() {
        let reached = Arc::new(AtomicBool::new(false));

        let pipeline = ToolPipeline::builder()
            .with_middleware(PermissionMiddleware::deny_all())
            .with_middleware(ReachTracker {
                reached: Arc::clone(&reached),
            })
            .with_core(test_registry())
            .build()
            .expect("valid");

        let _ = pipeline.invoke(test_ctx("echo")).await;
        assert!(
            !reached.load(Ordering::SeqCst),
            "middleware after deny should not be reached"
        );
    }

    struct LongOutputTool;

    impl Tool for LongOutputTool {
        fn name(&self) -> &'static str {
            "long_output"
        }

        fn description(&self) -> &'static str {
            "Returns a long string for testing"
        }

        fn schema(&self) -> ToolSchema {
            ToolSchema {
                tool: self.name().to_string(),
                description: self.description().to_string(),
                input_schema: serde_json::json!({"type": "object", "properties": {}}),
            }
        }

        fn call(
            &self,
            input: Value,
            _ctx: &ToolContext,
        ) -> Pin<Box<dyn Future<Output = Result<ToolOutput, ToolError>> + Send + '_>> {
            Box::pin(async move {
                let count = usize::try_from(
                    input
                        .get("count")
                        .and_then(serde_json::Value::as_u64)
                        .unwrap_or(100),
                )
                .unwrap();
                let ch = input.get("char").and_then(|v| v.as_str()).unwrap_or("a");
                Ok(ToolOutput::text(ch.repeat(count)))
            })
        }
    }

    struct MultipartTool;

    impl Tool for MultipartTool {
        fn name(&self) -> &'static str {
            "multipart"
        }

        fn description(&self) -> &'static str {
            "Returns multipart content"
        }

        fn schema(&self) -> ToolSchema {
            ToolSchema {
                tool: self.name().to_string(),
                description: self.description().to_string(),
                input_schema: serde_json::json!({"type": "object", "properties": {}}),
            }
        }

        fn call(
            &self,
            _input: Value,
            _ctx: &ToolContext,
        ) -> Pin<Box<dyn Future<Output = Result<ToolOutput, ToolError>> + Send + '_>> {
            Box::pin(async move {
                Ok(ToolOutput {
                    payload: ToolContent::Multipart(vec![
                        ToolContentPart::Text {
                            text: "part1".to_string(),
                        },
                        ToolContentPart::Text {
                            text: "part2".to_string(),
                        },
                    ]),
                    is_error: false,
                    display_hint: None,
                })
            })
        }
    }

    fn long_output_registry() -> Arc<ToolRegistry> {
        let mut registry = ToolRegistry::new();
        registry.register(LongOutputTool);
        registry.register(MultipartTool);
        Arc::new(registry)
    }

    fn long_output_ctx(tool_name: &str, count: usize) -> ToolDispatchContext {
        let mut ctx = test_ctx(tool_name);
        ctx.input = serde_json::json!({"count": count});
        ctx
    }

    #[tokio::test]
    async fn test_output_limit_short_text_passes_through() {
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(1000))
            .with_core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", 50)).await;
        assert!(!result.is_error);
        assert_eq!(result.output, ToolContent::Text("a".repeat(50)));
    }

    #[tokio::test]
    async fn test_output_limit_exact_limit_passes_through() {
        let registry = long_output_registry();
        let limit = 100;
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(limit))
            .with_core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", limit)).await;
        assert!(!result.is_error);
        assert_eq!(result.output, ToolContent::Text("a".repeat(limit)));
    }

    #[tokio::test]
    async fn test_output_limit_truncates_long_text() {
        let registry = long_output_registry();
        let limit = 50;
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(limit))
            .with_core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", 200)).await;
        assert!(!result.is_error);
        let expected = format!("{}\n[truncated]", "a".repeat(limit - 12));
        assert_eq!(result.output, ToolContent::Text(expected));
        let ToolContent::Text(text) = &result.output else {
            panic!("expected Text output")
        };
        let text_len = text.chars().count();
        assert_eq!(
            text_len, limit,
            "a truncated output is exactly at the cap — the marker is inside the budget"
        );
    }

    #[tokio::test]
    async fn test_output_limit_truncation_respects_char_boundary() {
        // Verify truncation operates on char boundaries, not bytes, and
        // that the marker is reserved inside the budget: a 15-char cap
        // keeps 3 é (each 2 bytes) plus the 12-char marker.
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(15))
            .with_core(Arc::clone(&registry))
            .build()
            .expect("valid");
        let mut ctx = test_ctx("long_output");
        ctx.input = serde_json::json!({"count": 30, "char": "é"});

        let result = pipeline.invoke(ctx).await;
        assert!(!result.is_error);
        let expected = format!("{}\n[truncated]", "é".repeat(3));
        assert_eq!(result.output, ToolContent::Text(expected));
    }

    #[tokio::test]
    async fn test_output_limit_multipart_text_parts_are_truncated() {
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(3))
            .with_core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("multipart")).await;
        assert!(!result.is_error);
        // The shared character budget (3) is smaller than the marker
        // (12), so the first text part collapses to the bare marker —
        // truncation must stay visible even at tiny budgets — and the
        // second gets zero remaining budget and is emptied.
        match result.output {
            ToolContent::Multipart(parts) => {
                assert_eq!(parts.len(), 2, "should still have 2 parts");
                match &parts[0] {
                    ToolContentPart::Text { text } => {
                        assert_eq!(
                            text, "\n[truncated]",
                            "part 0 keeps only the marker: got {text:?}"
                        );
                    }
                    ToolContentPart::Image { .. } => {
                        panic!("unexpected image part in MultipartTool output");
                    }
                }
                match &parts[1] {
                    ToolContentPart::Text { text } => {
                        assert_eq!(
                            text, "",
                            "a part with zero remaining budget is emptied, not re-marked: got {text:?}"
                        );
                    }
                    ToolContentPart::Image { .. } => {
                        panic!("unexpected image part in MultipartTool output");
                    }
                }
            }
            other @ ToolContent::Text(_) => panic!("expected Multipart, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_output_limit_multipart_short_parts_pass_through() {
        // When all text parts are within the limit, multipart should
        // pass through unchanged.
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(100))
            .with_core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("multipart")).await;
        assert!(!result.is_error);
        match result.output {
            ToolContent::Multipart(parts) => {
                assert_eq!(parts.len(), 2);
                match &parts[0] {
                    ToolContentPart::Text { text } => {
                        assert_eq!(text, "part1", "short part should not be truncated");
                    }
                    ToolContentPart::Image { .. } => panic!("expected Text part[0], got Image"),
                }
                match &parts[1] {
                    ToolContentPart::Text { text } => {
                        assert_eq!(text, "part2", "short part should not be truncated");
                    }
                    ToolContentPart::Image { .. } => panic!("expected Text part[1], got Image"),
                }
            }
            other @ ToolContent::Text(_) => panic!("expected Multipart, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn test_output_limit_error_output_is_truncated() {
        // When a tool produces an error with a long message, the
        // OutputLimitMiddleware should still truncate it.
        let registry = test_registry(); // has EchoTool
        let pipeline = ToolPipeline::builder()
            .with_middleware(PermissionMiddleware::deny_all())
            .with_middleware(OutputLimitMiddleware::new(10))
            .with_core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("echo")).await;
        assert!(result.is_error);
        // Permission denied messages are short, so they may or may not
        // be truncated. The key assertion is that the pipeline ran both
        // middlewares without panicking.
    }

    #[tokio::test]
    async fn test_output_limit_preserves_duration() {
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(10))
            .with_core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", 5000)).await;
        // Duration should reflect actual tool execution time, not be
        // zeroed out by the truncation middleware.
        assert!(
            result.duration > Duration::ZERO,
            "duration should be preserved after truncation"
        );
    }

    #[tokio::test]
    async fn test_output_limit_preserves_resolved_tool_name() {
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(10))
            .with_core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", 500)).await;
        assert_eq!(result.resolved_tool_name, "long_output");
    }

    #[tokio::test]
    async fn test_output_limit_stacked_with_timeout() {
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with_middleware(TimeoutMiddleware::from_secs(120))
            .with_middleware(OutputLimitMiddleware::new(20))
            .with_core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", 1000)).await;
        assert!(!result.is_error);
        let expected = format!("{}\n[truncated]", "a".repeat(20 - 12));
        assert_eq!(result.output, ToolContent::Text(expected));
    }

    #[tokio::test]
    async fn test_output_limit_zero_chars_disables_truncation() {
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(0))
            .with_core(Arc::clone(&registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(long_output_ctx("long_output", 100)).await;
        assert!(!result.is_error);
        let ToolContent::Text(text) = result.output else {
            panic!("expected Text output from the long-output tool")
        };
        assert_eq!(
            text.chars().count(),
            100,
            "a zero cap disables the middleware — output passes through untouched"
        );
    }

    #[tokio::test]
    async fn test_output_limit_multibyte_under_char_limit_not_truncated() {
        // "日" is 3 bytes. 5 repetitions = 5 chars, 15 bytes.
        // Set max_chars = 8: 5 chars < 8, but 15 bytes > 8.
        let registry = long_output_registry();
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(8))
            .with_core(Arc::clone(&registry))
            .build()
            .expect("valid");
        let ctx = ToolDispatchContext {
            tool_name: "long_output".to_string(),
            input: json!({"count": 5, "char": "日"}),
            call_id: "mb-1".to_string(),
            turn_number: 1,
            cancel: Arc::new(CancelSignal::new()),
            permission: PermissionCheck::Allow,
            tool_context: ToolContext::default(),
        };

        let result = pipeline.invoke(ctx).await;
        assert!(!result.is_error);
        // Must NOT be truncated: 5 chars <= 8 max_chars, even though 15 bytes > 8.
        assert_eq!(result.output, ToolContent::Text("日日日日日".to_string()));
    }

    #[test]
    fn from_result_maps_ok_output() {
        let output = ToolOutput::text("hello");
        let result = ToolDispatchResult::from_result("echo", Ok(output), Duration::from_millis(50));
        assert!(!result.is_error);
        assert_eq!(result.output, ToolContent::Text("hello".to_string()));
        assert_eq!(result.resolved_tool_name, "echo");
        assert_eq!(result.duration, Duration::from_millis(50));
    }

    #[test]
    fn from_result_maps_err_to_error_result() {
        let error = ToolError::not_found("missing_tool", &[]);
        let result =
            ToolDispatchResult::from_result("missing_tool", Err(error), Duration::from_millis(10));
        assert!(result.is_error);
        assert_eq!(result.resolved_tool_name, "missing_tool");
    }

    #[test]
    fn from_tool_output_defaults() {
        let output = ToolOutput::text("ok");
        let result = ToolDispatchResult::from(output);
        assert!(!result.is_error);
        assert_eq!(result.output, ToolContent::Text("ok".to_string()));
        assert_eq!(result.duration, Duration::ZERO);
        assert_eq!(result.resolved_tool_name, "");
    }

    #[test]
    fn from_tool_output_error_preserves_is_error() {
        let output = ToolOutput::error_text("boom");
        let result = ToolDispatchResult::from(output);
        assert!(result.is_error);
        assert_eq!(result.output, ToolContent::Text("boom".to_string()));
    }

    #[test]
    fn builder_methods_chain() {
        let output = ToolOutput::text("done");
        let result = ToolDispatchResult::from(output)
            .with_tool_name("bash")
            .with_duration(Duration::from_millis(99));
        assert_eq!(result.resolved_tool_name, "bash");
        assert_eq!(result.duration, Duration::from_millis(99));
        assert!(!result.is_error);
    }

    /// A tool that returns 3 text parts, each individually under the limit
    /// but collectively exceeding it.
    struct ThreePartTextTool;

    impl Tool for ThreePartTextTool {
        fn name(&self) -> &'static str {
            "three_part_text"
        }

        fn description(&self) -> &'static str {
            "Returns 3 short text parts"
        }

        fn schema(&self) -> ToolSchema {
            ToolSchema {
                tool: self.name().to_string(),
                description: self.description().to_string(),
                input_schema: json!({"type": "object", "properties": {}}),
            }
        }

        fn call(
            &self,
            _input: Value,
            _ctx: &ToolContext,
        ) -> Pin<Box<dyn Future<Output = Result<ToolOutput, ToolError>> + Send + '_>> {
            Box::pin(async move {
                Ok(ToolOutput {
                    payload: ToolContent::Multipart(vec![
                        ToolContentPart::Text {
                            text: "aaaa".to_string(),
                        },
                        ToolContentPart::Text {
                            text: "bbbb".to_string(),
                        },
                        ToolContentPart::Text {
                            text: "cccc".to_string(),
                        },
                    ]),
                    is_error: false,
                    display_hint: None,
                })
            })
        }
    }

    #[tokio::test]
    async fn output_limit_multipart_shared_budget_truncates_later_parts() {
        // max_chars = 6: part 0 (4) fits, leaving 2.
        // Part 1 (4 > 2) collapses to the bare marker (2 < marker 12).
        // Part 2 → 0 remaining, emptied.
        let mut registry = ToolRegistry::new();
        registry.register(ThreePartTextTool);
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(6))
            .with_core(Arc::new(registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("three_part_text")).await;
        assert!(!result.is_error);

        match result.output {
            ToolContent::Multipart(parts) => {
                assert_eq!(parts.len(), 3);
                match &parts[0] {
                    ToolContentPart::Text { text } => {
                        assert_eq!(text, "aaaa", "part 0 should be unmodified");
                    }
                    ToolContentPart::Image { .. } => panic!("expected Text part 0"),
                }
                match &parts[1] {
                    ToolContentPart::Text { text } => {
                        assert_eq!(
                            text, "\n[truncated]",
                            "part 1 keeps only the marker (remaining 2 < marker): got {text:?}"
                        );
                    }
                    ToolContentPart::Image { .. } => panic!("expected Text part 1"),
                }
                match &parts[2] {
                    ToolContentPart::Text { text } => {
                        assert_eq!(
                            text, "",
                            "part 2 should be emptied with zero budget: got {text:?}"
                        );
                    }
                    ToolContentPart::Image { .. } => panic!("expected Text part 2"),
                }
            }
            ToolContent::Text(t) => panic!("expected Multipart, got Text({t})"),
        }
    }

    #[tokio::test]
    async fn output_limit_multipart_shared_budget_all_fit() {
        // max_chars = 20: all three 4-char parts (12 total) fit.
        let mut registry = ToolRegistry::new();
        registry.register(ThreePartTextTool);
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(20))
            .with_core(Arc::new(registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("three_part_text")).await;
        assert!(!result.is_error);

        match result.output {
            ToolContent::Multipart(parts) => {
                assert_eq!(parts.len(), 3);
                for (i, part) in parts.iter().enumerate() {
                    match part {
                        ToolContentPart::Text { text } => {
                            assert!(
                                !text.contains("[truncated]"),
                                "part {i} should not be truncated: got {text:?}"
                            );
                        }
                        ToolContentPart::Image { .. } => panic!("expected Text part {i}"),
                    }
                }
            }
            ToolContent::Text(t) => panic!("expected Multipart, got Text({t})"),
        }
    }

    #[tokio::test]
    async fn output_limit_multipart_shared_budget_exactly_consumed() {
        // max_chars = 8: parts 0+1 (4+4) exactly consume the budget.
        // Part 2 → 0 remaining → "[truncated]".
        let mut registry = ToolRegistry::new();
        registry.register(ThreePartTextTool);
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(8))
            .with_core(Arc::new(registry))
            .build()
            .expect("valid");

        let result = pipeline.invoke(test_ctx("three_part_text")).await;
        assert!(!result.is_error);

        match result.output {
            ToolContent::Multipart(parts) => {
                assert_eq!(parts.len(), 3);
                match &parts[0] {
                    ToolContentPart::Text { text } => {
                        assert_eq!(text, "aaaa", "part 0 unmodified");
                    }
                    ToolContentPart::Image { .. } => panic!("expected Text part 0"),
                }
                match &parts[1] {
                    ToolContentPart::Text { text } => {
                        assert_eq!(text, "bbbb", "part 1 unmodified");
                    }
                    ToolContentPart::Image { .. } => panic!("expected Text part 1"),
                }
                match &parts[2] {
                    ToolContentPart::Text { text } => {
                        assert_eq!(
                            text, "",
                            "part 2 should be emptied with zero budget: got {text:?}"
                        );
                    }
                    ToolContentPart::Image { .. } => panic!("expected Text part 2"),
                }
            }
            ToolContent::Text(t) => panic!("expected Multipart, got Text({t})"),
        }
    }

    /// A tool that returns two text parts, the second larger than the
    /// budget the first leaves.
    struct SizedPartsTool;

    impl Tool for SizedPartsTool {
        fn name(&self) -> &'static str {
            "sized_parts"
        }
        fn description(&self) -> &'static str {
            "Returns two text parts of 80 and 40 chars"
        }
        fn schema(&self) -> ToolSchema {
            ToolSchema {
                tool: self.name().to_string(),
                description: self.description().to_string(),
                input_schema: json!({"type": "object", "properties": {}}),
            }
        }
        fn call(
            &self,
            _input: Value,
            _ctx: &ToolContext,
        ) -> Pin<Box<dyn Future<Output = Result<ToolOutput, ToolError>> + Send + '_>> {
            Box::pin(async move {
                Ok(ToolOutput {
                    payload: ToolContent::Multipart(vec![
                        ToolContentPart::Text {
                            text: "a".repeat(80),
                        },
                        ToolContentPart::Text {
                            text: "b".repeat(40),
                        },
                    ]),
                    is_error: false,
                    display_hint: None,
                })
            })
        }
    }

    #[tokio::test]
    async fn output_limit_multipart_shares_one_budget() {
        // The cap is one whole-output budget, not a per-part allowance:
        // the 80-char first part consumes 80 of the 100 chars, so the
        // 40-char second part is cut to the 20 that remain.
        let mut registry = ToolRegistry::new();
        registry.register(SizedPartsTool);
        let pipeline = ToolPipeline::builder()
            .with_middleware(OutputLimitMiddleware::new(100))
            .with_core(Arc::new(registry))
            .build()
            .expect("pipeline builds");

        let result = pipeline.invoke(test_ctx("sized_parts")).await;
        match result.output {
            ToolContent::Multipart(parts) => {
                assert_eq!(
                    parts.len(),
                    2,
                    "the cap truncates in place, it never resizes"
                );
                match &parts[0] {
                    ToolContentPart::Text { text } => {
                        assert_eq!(
                            text,
                            &"a".repeat(80),
                            "part 0 fits the shared budget and passes unchanged: got {text:?}"
                        );
                    }
                    ToolContentPart::Image { .. } => panic!("expected Text part 0"),
                }
                match &parts[1] {
                    ToolContentPart::Text { text } => {
                        assert_eq!(
                            text,
                            &format!("{}\n[truncated]", "b".repeat(8)),
                            "part 1 gets the 20 remaining chars minus the marker (12): got {text:?}"
                        );
                    }
                    ToolContentPart::Image { .. } => panic!("expected Text part 1"),
                }
            }
            other @ ToolContent::Text(_) => panic!("expected Multipart, got {other:?}"),
        }
    }
}
